import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Providers} from "@/components";
import { exo } from "@/lib/fonts";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${exo.className} antialiased flex`}
      >

        {/* Provedor de sesion */}
        <Providers>

              <main className="w-full">

                {/* Main Content */}
                <div className="">
                  {children}
                </div>

              </main>

              
              <Toaster richColors expand={true}/>{/* Sonner */}

        </Providers>

      </body>
    </html>
  );
}
