import type { Metadata } from "next";
import { AppSideBar } from "@/components/dashboard/sidebar/AppSideBar";
import { Navbar } from "@/components/dashboard/Navbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { AppBreadcrumb } from "@/components/dashboard/AppBreadcrumb";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const cookieStore = await cookies()
    const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  
    return (

        <div className="overflow-y-auto h-screen">

            <SidebarProvider defaultOpen={defaultOpen}>
            
                <AppSideBar/> {/* Sidebar */}

                <main className="w-full">
                
                    <Navbar/> {/* Navbar */}
                    
                    <AppBreadcrumb /> {/* Breadcrumb */}
                    
                    {/* Main Content */}
                    <div className="px-4">
                        {children}
                    </div>

                </main>

            </SidebarProvider>

        </div>
    );
}
