interface SeedCiudad {
    id_state: string
    name: string,
}

export const ciudades: SeedCiudad[] = [
    { id_state: "1", name: "Artigas" },
    { id_state: "1", name: "Baltasar Brum" },
    { id_state: "1", name: "Bella Union" },
    { id_state: "1", name: "Bernabe Rivera" },
    { id_state: "1", name: "Cainsa" },
    { id_state: "1", name: "Cainza Campo 3" },
    { id_state: "1", name: "Calnu" },
    { id_state: "1", name: "Camaño" },
    { id_state: "1", name: "Catalan Grande" },
    { id_state: "1", name: "Catalan Volcan" },
    { id_state: "1", name: "Cerrito" },
    { id_state: "1", name: "Cerro Ejido" },
    { id_state: "1", name: "Cerro San Eugenio" },
    { id_state: "1", name: "Cerro Signorelli" },
    { id_state: "1", name: "Chiflero" },
    { id_state: "1", name: "Colonia España" },
    { id_state: "1", name: "Colonia Estrella" },
    { id_state: "1", name: "Colonia José Artigas" },
    { id_state: "1", name: "Colonia Palma" },
    { id_state: "1", name: "Colonia Pintado" },
    { id_state: "1", name: "Colonia Viñar" },
    { id_state: "1", name: "Coronado" },
    { id_state: "1", name: "Cuareim" },
    { id_state: "1", name: "Cuaro" },
    { id_state: "1", name: "Diego Lamas" },
    { id_state: "1", name: "Estiba" },
    { id_state: "1", name: "Fagúndez" },
    { id_state: "1", name: "Franquía" },
    { id_state: "1", name: "Guyubira" },
    { id_state: "1", name: "Javier De Viana" },
    { id_state: "1", name: "La Bolsa" },
    { id_state: "1", name: "Las Piedras" },
    { id_state: "1", name: "Lenguazo" },
    { id_state: "1", name: "Limite Contestado" },
    { id_state: "1", name: "Masoller" },
    { id_state: "1", name: "Meneses" },
    { id_state: "1", name: "Mones Quintela" },
    { id_state: "1", name: "Paguero" },
    { id_state: "1", name: "Palma Sola" },
    { id_state: "1", name: "Paredón" },
    { id_state: "1", name: "Paso Campamento" },
    { id_state: "1", name: "Paso De La Cruz" },
    { id_state: "1", name: "Paso De León" },
    { id_state: "1", name: "Paso De Ramos" },
    { id_state: "1", name: "Paso Farías" },
    { id_state: "1", name: "Patitas" },
    { id_state: "1", name: "Piedra Pintada" },
    { id_state: "1", name: "Pintadito" },
    { id_state: "1", name: "Pintado" },
    { id_state: "1", name: "Pintado Grande" },
    { id_state: "1", name: "Port. De Hierro Y Campodónico" },
    { id_state: "1", name: "Rincón De Pacheco" },
    { id_state: "1", name: "Sarandí De Cuaro" },
    { id_state: "1", name: "Sarandí De Yacuy" },
    { id_state: "1", name: "Sequeira" },
    { id_state: "1", name: "Tamandua" },
    { id_state: "1", name: "Taruman" },
    { id_state: "1", name: "Tomas Gomensoro" },
    { id_state: "1", name: "Topador" },
    { id_state: "1", name: "Zanja Aruera" },
    { id_state: "2", name: "Aeropuerto Internacional De Carrasco" },
    { id_state: "2", name: "Aguas Corrientes" },
    { id_state: "2", name: "Altos De La Tahona" },
    { id_state: "2", name: "Araminda" },
    { id_state: "2", name: "Arenal" },
    { id_state: "2", name: "Argentino" },
    { id_state: "2", name: "Atlantida" },
    { id_state: "2", name: "B.h.u." },
    { id_state: "2", name: "Barra De Carrasco" },
    { id_state: "2", name: "Barra De La Pedrera" },
    { id_state: "2", name: "Barra Del Tala" },
    { id_state: "2", name: "Barrancas Coloradas" },
    { id_state: "2", name: "Barrío Artigas" },
    { id_state: "2", name: "Barrío Benzo" },
    { id_state: "2", name: "Barrío Copola" },
    { id_state: "2", name: "Barrío Del Libertador" },
    { id_state: "2", name: "Barrío La Lucha" },
    { id_state: "2", name: "Barrío Los Panoramas" },
    { id_state: "2", name: "Barrío Obrero" },
    { id_state: "2", name: "Barrío Pretti" },
    { id_state: "2", name: "Barrío Remanso" },
    { id_state: "2", name: "Barrío San Cristobal" },
    { id_state: "2", name: "Barrío Santa Rita" },
    { id_state: "2", name: "Barrío Traverso" },
    { id_state: "2", name: "Barrío Villa Murcia" },
    { id_state: "2", name: "Barros Blancos" },
    { id_state: "2", name: "Bello Horizonte" },
    { id_state: "2", name: "Biarritz" },
    { id_state: "2", name: "Blanco" },
    { id_state: "2", name: "Bolivar" },
    { id_state: "2", name: "Camino De La Cadena" },
    { id_state: "2", name: "Camino Dodera" },
    { id_state: "2", name: "Camino Lloveras" },
    { id_state: "2", name: "Campo Militar" },
    { id_state: "2", name: "Cañada Cardozo" },
    { id_state: "2", name: "Cañada De Montaño" },
    { id_state: "2", name: "Cañada Grande" },
    { id_state: "2", name: "Cañada Prudencio" },
    { id_state: "2", name: "Canelon Chico" },
    { id_state: "2", name: "Canelon Chico Al Centro" },
    { id_state: "2", name: "Canelon Chico De Progreso" },
    { id_state: "2", name: "Canelon Grande" },
    { id_state: "2", name: "Canelon Grande De Pacheco" },
    { id_state: "2", name: "Canelon Grande Norte" },
    { id_state: "2", name: "Canelones" },
    { id_state: "2", name: "Capilla De Cella" },
    { id_state: "2", name: "Carmel" },
    { id_state: "2", name: "Carrasco Del Sauce" },
    { id_state: "2", name: "Casarino" },
    { id_state: "2", name: "Castellanos" },
    { id_state: "2", name: "Cerrillos" },
    { id_state: "2", name: "Cerrillos Al Oeste" },
    { id_state: "2", name: "Cerrillos Al Sur" },
    { id_state: "2", name: "City Golf" },
    { id_state: "2", name: "Ciudad De La Costa" },
    { id_state: "2", name: "Cochengo" },
    { id_state: "2", name: "Colinas De Carrasco" },
    { id_state: "2", name: "Colinas De Solymar" },
    { id_state: "2", name: "Colonia Nicolich" },
    { id_state: "2", name: "Colorado Chico" },
    { id_state: "2", name: "Colorado Y Brujas" },
    { id_state: "2", name: "Costa Azul" },
    { id_state: "2", name: "Costa De Pando" },
    { id_state: "2", name: "Costa De Pando Olmos" },
    { id_state: "2", name: "Costa De Pando San Bautista" },
    { id_state: "2", name: "Costa De Pando San Jacinto" },
    { id_state: "2", name: "Costa Del Sauce" },
    { id_state: "2", name: "Costa Del Tala Este" },
    { id_state: "2", name: "Costa Del Tala Norte" },
    { id_state: "2", name: "Costa Y Guillamon" },
    { id_state: "2", name: "Costas De Pedernal" },
    { id_state: "2", name: "Costas De Santa Lucia" },
    { id_state: "2", name: "Costas De Solís" },
    { id_state: "2", name: "Costas Del Colorado" },
    { id_state: "2", name: "Costas Del Colorado Este" },
    { id_state: "2", name: "Costas Del Tala" },
    { id_state: "2", name: "Cruz De Los Caminos" },
    { id_state: "2", name: "Cuchilla Alta" },
    { id_state: "2", name: "Cuchilla Cabo De Hornos" },
    { id_state: "2", name: "Cuchilla De Machin" },
    { id_state: "2", name: "Cuchilla De Rocha" },
    { id_state: "2", name: "Cuchilla De Sierra" },
    { id_state: "2", name: "Cuchilla De Zeballos" },
    { id_state: "2", name: "Cuchilla Verde" },
    { id_state: "2", name: "Cueva Del Tigre" },
    { id_state: "2", name: "Cumbres De Carrasco" },
    { id_state: "2", name: "Dr. Francisco Soca" },
    { id_state: "2", name: "Echevarria" },
    { id_state: "2", name: "El Bosque" },
    { id_state: "2", name: "El Bosque De Solymar" },
    { id_state: "2", name: "El Colorado" },
    { id_state: "2", name: "El Colorado De Migues" },
    { id_state: "2", name: "El Colorado San Bautista" },
    { id_state: "2", name: "El Cuadro" },
    { id_state: "2", name: "El Dorado" },
    { id_state: "2", name: "El Galeón" },
    { id_state: "2", name: "El Pinar" },
    { id_state: "2", name: "Empalme Dogliotti" },
    { id_state: "2", name: "Empalme Nicolich" },
    { id_state: "2", name: "Empalme Olmos" },
    { id_state: "2", name: "Empalme Sauce" },
    { id_state: "2", name: "Esquina Gonzalez" },
    { id_state: "2", name: "Estación Atlantida" },
    { id_state: "2", name: "Estación La Floresta" },
    { id_state: "2", name: "Estación Migues" },
    { id_state: "2", name: "Estación Pedrera" },
    { id_state: "2", name: "Estación Piedras De Afilar" },
    { id_state: "2", name: "Estación Tapia" },
    { id_state: "2", name: "Estanque De Pando" },
    { id_state: "2", name: "Feliciano" },
    { id_state: "2", name: "Fortin De Santa Rosa" },
    { id_state: "2", name: "Fracc Sobre Ruta 74" },
    { id_state: "2", name: "Fracc. Cno. Andaluz Y R.84" },
    { id_state: "2", name: "Fracc. Progreso" },
    { id_state: "2", name: "Guazuvira" },
    { id_state: "2", name: "Guazuvira Nuevo" },
    { id_state: "2", name: "Haras Del Lago" },
    { id_state: "2", name: "Instituto Adventista" },
    { id_state: "2", name: "Jardínes De Pando" },
    { id_state: "2", name: "Jaureguiberry" },
    { id_state: "2", name: "Joaquín Suarez" },
    { id_state: "2", name: "Juanico" },
    { id_state: "2", name: "La Asuncion" },
    { id_state: "2", name: "La Chinchilla" },
    { id_state: "2", name: "La Floresta" },
    { id_state: "2", name: "La Montañesa" },
    { id_state: "2", name: "La Palmita" },
    { id_state: "2", name: "La Paloma" },
    { id_state: "2", name: "La Paz" },
    { id_state: "2", name: "La Totora" },
    { id_state: "2", name: "La Tuna" },
    { id_state: "2", name: "Lago Jardín Del Bosque" },
    { id_state: "2", name: "Lagomar" },
    { id_state: "2", name: "Las Brujas" },
    { id_state: "2", name: "Las Higueritas" },
    { id_state: "2", name: "Las Piedras" },
    { id_state: "2", name: "Las Ranas" },
    { id_state: "2", name: "Las Toscas" },
    { id_state: "2", name: "Las Vegas" },
    { id_state: "2", name: "Las Violetas" },
    { id_state: "2", name: "Lomas De Carrasco" },
    { id_state: "2", name: "Lomas De Solymar" },
    { id_state: "2", name: "Lomas De Toledo" },
    { id_state: "2", name: "Los Ceibos" },
    { id_state: "2", name: "Los Hornos" },
    { id_state: "2", name: "Los Titanes" },
    { id_state: "2", name: "Macana" },
    { id_state: "2", name: "Margat" },
    { id_state: "2", name: "Marindia" },
    { id_state: "2", name: "Mata Siete" },
    { id_state: "2", name: "Mataojo" },
    { id_state: "2", name: "Medanos De Solymar" },
    { id_state: "2", name: "Melgarejo" },
    { id_state: "2", name: "Melilla" },
    { id_state: "2", name: "Migues" },
    { id_state: "2", name: "Montes" },
    { id_state: "2", name: "Montes De Solymar" },
    { id_state: "2", name: "Murialdo" },
    { id_state: "2", name: "Nataly" },
    { id_state: "2", name: "Neptunia" },
    { id_state: "2", name: "Nutrias" },
    { id_state: "2", name: "Olmos" },
    { id_state: "2", name: "Pando" },
    { id_state: "2", name: "Pantanoso" },
    { id_state: "2", name: "Pantanoso Del Sauce" },
    { id_state: "2", name: "Parada Cabrera" },
    { id_state: "2", name: "Parador Tajes" },
    { id_state: "2", name: "Parque Carrasco" },
    { id_state: "2", name: "Parque De Solymar" },
    { id_state: "2", name: "Parque Del Plata" },
    { id_state: "2", name: "Parque Miramar" },
    { id_state: "2", name: "Paso Arbelo" },
    { id_state: "2", name: "Paso Carrasco" },
    { id_state: "2", name: "Paso De Cuello" },
    { id_state: "2", name: "Paso De La Cadena" },
    { id_state: "2", name: "Paso De La Paloma" },
    { id_state: "2", name: "Paso De La Salamanca" },
    { id_state: "2", name: "Paso De Las Toscas" },
    { id_state: "2", name: "Paso De Los Alamos" },
    { id_state: "2", name: "Paso De Los Difuntos" },
    { id_state: "2", name: "Paso De Los Francos" },
    { id_state: "2", name: "Paso De Pache" },
    { id_state: "2", name: "Paso Del Bote" },
    { id_state: "2", name: "Paso Del Colorado" },
    { id_state: "2", name: "Paso Del Sordo" },
    { id_state: "2", name: "Paso Espinosa" },
    { id_state: "2", name: "Paso Palomeque" },
    { id_state: "2", name: "Paso Rivero De Vejigas" },
    { id_state: "2", name: "Pedernal" },
    { id_state: "2", name: "Pedernal Chico" },
    { id_state: "2", name: "Pedernal Grande" },
    { id_state: "2", name: "Piedra Del Toro" },
    { id_state: "2", name: "Piedra Sola" },
    { id_state: "2", name: "Piedras De Afilar" },
    { id_state: "2", name: "Piedritas" },
    { id_state: "2", name: "Piedritas De Suarez" },
    { id_state: "2", name: "Pinamar" },
    { id_state: "2", name: "Pinares De Solymar" },
    { id_state: "2", name: "Pine Park" },
    { id_state: "2", name: "Ponce Mata Siete" },
    { id_state: "2", name: "Poquitos" },
    { id_state: "2", name: "Progreso" },
    { id_state: "2", name: "Puente De Brujas" },
    { id_state: "2", name: "Puntas De Brujas" },
    { id_state: "2", name: "Puntas De Cañada Cardozo" },
    { id_state: "2", name: "Puntas De Cañada Grande" },
    { id_state: "2", name: "Puntas De Canelon Chico" },
    { id_state: "2", name: "Puntas De Cochengo" },
    { id_state: "2", name: "Puntas De Las Violetas" },
    { id_state: "2", name: "Puntas De Mata Siete" },
    { id_state: "2", name: "Puntas De Pantanoso" },
    { id_state: "2", name: "Puntas De Pantanoso Este" },
    { id_state: "2", name: "Puntas De Pedrera" },
    { id_state: "2", name: "Puntas De Vejigas" },
    { id_state: "2", name: "Puntas Del Arenal" },
    { id_state: "2", name: "Quinta Los Horneros" },
    { id_state: "2", name: "Quintas Del Bosque" },
    { id_state: "2", name: "Rancheríos De Ponce" },
    { id_state: "2", name: "Rincón De Pando" },
    { id_state: "2", name: "Rincón De Portezuelo" },
    { id_state: "2", name: "Rincón De Velazquez" },
    { id_state: "2", name: "Rincón De Vidal" },
    { id_state: "2", name: "Rincón Del Colorado" },
    { id_state: "2", name: "Rincón Del Conde" },
    { id_state: "2", name: "Rincón Del Gigante" },
    { id_state: "2", name: "Salinas" },
    { id_state: "2", name: "San Andres" },
    { id_state: "2", name: "San Antonio" },
    { id_state: "2", name: "San Bautista" },
    { id_state: "2", name: "San Jacinto" },
    { id_state: "2", name: "San José De Carrasco" },
    { id_state: "2", name: "San Luis" },
    { id_state: "2", name: "San Pedro" },
    { id_state: "2", name: "San Ramón" },
    { id_state: "2", name: "Santa Ana" },
    { id_state: "2", name: "Santa Lucia" },
    { id_state: "2", name: "Santa Lucia Del Este" },
    { id_state: "2", name: "Santa Rosa" },
    { id_state: "2", name: "Santa Teresita" },
    { id_state: "2", name: "Santos Lugares" },
    { id_state: "2", name: "Sarandí De Migues" },
    { id_state: "2", name: "Sauce" },
    { id_state: "2", name: "Sauce De Solís" },
    { id_state: "2", name: "Sauce Solo" },
    { id_state: "2", name: "Sauce Solo De Migues" },
    { id_state: "2", name: "Sauce Solo De Montes" },
    { id_state: "2", name: "Seis Hermanos" },
    { id_state: "2", name: "Shangrila" },
    { id_state: "2", name: "Sofia Santos" },
    { id_state: "2", name: "Solís Chico" },
    { id_state: "2", name: "Solís Chico De Migues" },
    { id_state: "2", name: "Solymar" },
    { id_state: "2", name: "Sosa Diaz" },
    { id_state: "2", name: "Tala" },
    { id_state: "2", name: "Talita" },
    { id_state: "2", name: "Toledo" },
    { id_state: "2", name: "Totoral Del Sauce" },
    { id_state: "2", name: "Vejigas" },
    { id_state: "2", name: "Vejigas De San Ramón" },
    { id_state: "2", name: "Vejigas De Tala" },
    { id_state: "2", name: "Viejo Molino San Bernardo" },
    { id_state: "2", name: "Villa Aeroparque" },
    { id_state: "2", name: "Villa Arejo" },
    { id_state: "2", name: "Villa Argentina" },
    { id_state: "2", name: "Villa Crespo" },
    { id_state: "2", name: "Villa El Tato" },
    { id_state: "2", name: "Villa Encantada" },
    { id_state: "2", name: "Villa Felicidad" },
    { id_state: "2", name: "Villa Foresti" },
    { id_state: "2", name: "Villa Fortuna" },
    { id_state: "2", name: "Villa Hadita" },
    { id_state: "2", name: "Villa Huertos De Toledo" },
    { id_state: "2", name: "Villa Juana" },
    { id_state: "2", name: "Villa Juanita" },
    { id_state: "2", name: "Villa Los Alpes" },
    { id_state: "2", name: "Villa Marina" },
    { id_state: "2", name: "Villa Molfino" },
    { id_state: "2", name: "Villa Nueva" },
    { id_state: "2", name: "Villa Paz S.a." },
    { id_state: "2", name: "Villa Prados De Toledo" },
    { id_state: "2", name: "Villa San Cono" },
    { id_state: "2", name: "Villa San Felipe" },
    { id_state: "2", name: "Villa San José" },
    { id_state: "2", name: "Villa Valverde" },
    { id_state: "2", name: "Vista Linda" },
    { id_state: "3", name: "Acegua" },
    { id_state: "3", name: "Aguirre" },
    { id_state: "3", name: "Amarillo" },
    { id_state: "3", name: "Arachania" },
    { id_state: "3", name: "Arbolito" },
    { id_state: "3", name: "Arevalo" },
    { id_state: "3", name: "Arroyo Malo" },
    { id_state: "3", name: "Arrozal Cesarone" },
    { id_state: "3", name: "Arrozal Rosales" },
    { id_state: "3", name: "Asperezas" },
    { id_state: "3", name: "Bañado De Las Pajas" },
    { id_state: "3", name: "Bañado De Medina" },
    { id_state: "3", name: "Barra Del Sauce" },
    { id_state: "3", name: "Barra Del Tacuari" },
    { id_state: "3", name: "Barrío La Vinchuca" },
    { id_state: "3", name: "Barrío Lopez Benitez" },
    { id_state: "3", name: "Berachi" },
    { id_state: "3", name: "Buena Vista" },
    { id_state: "3", name: "Calera De Recalde" },
    { id_state: "3", name: "Campamento" },
    { id_state: "3", name: "Cañada Brava" },
    { id_state: "3", name: "Cañada De Santos" },
    { id_state: "3", name: "Cañada Grande" },
    { id_state: "3", name: "Cañada Sarandí" },
    { id_state: "3", name: "Cañitas" },
    { id_state: "3", name: "Casa De Las Cronicas" },
    { id_state: "3", name: "Caserío Las Cañas" },
    { id_state: "3", name: "Cementerío" },
    { id_state: "3", name: "Centuríon" },
    { id_state: "3", name: "Cerro De Las Cuentas" },
    { id_state: "3", name: "Chacras De Melo" },
    { id_state: "3", name: "Coimbra" },
    { id_state: "3", name: "Colonia Ceres" },
    { id_state: "3", name: "Colonia Maria Teresa" },
    { id_state: "3", name: "Colonia Orozco" },
    { id_state: "3", name: "Conventos" },
    { id_state: "3", name: "Corral De Piedra" },
    { id_state: "3", name: "Cruz De Piedra" },
    { id_state: "3", name: "Cuchilla Cambota" },
    { id_state: "3", name: "Cuchilla De Melo" },
    { id_state: "3", name: "Cuchilla Del Carmen" },
    { id_state: "3", name: "Cuchilla Del Paraiso" },
    { id_state: "3", name: "Cuchilla Peralta" },
    { id_state: "3", name: "Duraznero" },
    { id_state: "3", name: "Escuela De Agronomia" },
    { id_state: "3", name: "Esperanza" },
    { id_state: "3", name: "Falda De Sierra De Los Ríos" },
    { id_state: "3", name: "Fraile Muerto" },
    { id_state: "3", name: "Ganen" },
    { id_state: "3", name: "Garao" },
    { id_state: "3", name: "Granja De Acegua" },
    { id_state: "3", name: "Granja Pallero" },
    { id_state: "3", name: "Guazunambi" },
    { id_state: "3", name: "Hipodromo" },
    { id_state: "3", name: "Infiernillo" },
    { id_state: "3", name: "Isidoro Noblia" },
    { id_state: "3", name: "La Coronilla" },
    { id_state: "3", name: "La Gloria" },
    { id_state: "3", name: "La Micaela" },
    { id_state: "3", name: "La Mina" },
    { id_state: "3", name: "La Pedrera" },
    { id_state: "3", name: "Laguna Del Junco" },
    { id_state: "3", name: "Laguna Merin" },
    { id_state: "3", name: "Las Limas" },
    { id_state: "3", name: "Los Cerros" },
    { id_state: "3", name: "Mangrullo" },
    { id_state: "3", name: "Maria Isabel" },
    { id_state: "3", name: "Mazangano" },
    { id_state: "3", name: "Melo" },
    { id_state: "3", name: "Minuano De Acegua" },
    { id_state: "3", name: "Misterío" },
    { id_state: "3", name: "Montecito" },
    { id_state: "3", name: "Nando" },
    { id_state: "3", name: "Ñangapire" },
    { id_state: "3", name: "Panteon" },
    { id_state: "3", name: "Paso De La Cruz" },
    { id_state: "3", name: "Paso De Las Tropas" },
    { id_state: "3", name: "Paso De Las Yeguas" },
    { id_state: "3", name: "Paso De Los Carros" },
    { id_state: "3", name: "Paso Melo" },
    { id_state: "3", name: "Paso Pereira" },
    { id_state: "3", name: "Peñarol" },
    { id_state: "3", name: "Picada De Maya" },
    { id_state: "3", name: "Picada De Salome" },
    { id_state: "3", name: "Piedra Alta" },
    { id_state: "3", name: "Piñeiro" },
    { id_state: "3", name: "Placido Rosas" },
    { id_state: "3", name: "Poblado Uruguay" },
    { id_state: "3", name: "Presidente Doctor Getulio Vargas" },
    { id_state: "3", name: "Puente Negro" },
    { id_state: "3", name: "Puntas De Amarillo" },
    { id_state: "3", name: "Puntas De La Mina" },
    { id_state: "3", name: "Puntas De Molles" },
    { id_state: "3", name: "Puntas De Palleros" },
    { id_state: "3", name: "Puntas De Tacuari" },
    { id_state: "3", name: "Puntas Del Sauce" },
    { id_state: "3", name: "Quebracho" },
    { id_state: "3", name: "Ramón Trigo" },
    { id_state: "3", name: "Rincón De Contreras" },
    { id_state: "3", name: "Rincón De La Urbana" },
    { id_state: "3", name: "Rincón De Los Coroneles" },
    { id_state: "3", name: "Rincón De Los Olivera" },
    { id_state: "3", name: "Rincón De Paiva" },
    { id_state: "3", name: "Rincón De Py" },
    { id_state: "3", name: "Rincón De Suarez" },
    { id_state: "3", name: "Rincón De Tacuari" },
    { id_state: "3", name: "Río Branco" },
    { id_state: "3", name: "Rodriguez" },
    { id_state: "3", name: "Saldañas" },
    { id_state: "3", name: "San Diego" },
    { id_state: "3", name: "San Servando" },
    { id_state: "3", name: "Sanchez" },
    { id_state: "3", name: "Santa Teresa" },
    { id_state: "3", name: "Sarandí De Acegua" },
    { id_state: "3", name: "Sarandí De Barcelo" },
    { id_state: "3", name: "Sarandí De Yaguaron" },
    { id_state: "3", name: "Sauce De Conventos" },
    { id_state: "3", name: "Soto Goro" },
    { id_state: "3", name: "Toledo" },
    { id_state: "3", name: "Tres Boliches" },
    { id_state: "3", name: "Tres Islas" },
    { id_state: "3", name: "Tupambaé" },
    { id_state: "3", name: "Villa Viñoles" },
    { id_state: "3", name: "Wenceslao Silvera" },
    { id_state: "4", name: "Agraciada" },
    { id_state: "4", name: "Arrivillaga" },
    { id_state: "4", name: "Artilleros" },
    { id_state: "4", name: "Barker" },
    { id_state: "4", name: "Barker Norte" },
    { id_state: "4", name: "Barrancas Coloradas" },
    { id_state: "4", name: "Barrío Mendaña" },
    { id_state: "4", name: "Barrío Olimpico" },
    { id_state: "4", name: "Belgrano Norte" },
    { id_state: "4", name: "Belgrano Sur" },
    { id_state: "4", name: "Blanca Arena" },
    { id_state: "4", name: "Boca Del Rosario" },
    { id_state: "4", name: "Boca Del Rosario Oeste" },
    { id_state: "4", name: "Bonjour" },
    { id_state: "4", name: "Brisas Del Plata" },
    { id_state: "4", name: "Buena Hora" },
    { id_state: "4", name: "Campamento Artigas" },
    { id_state: "4", name: "Campana" },
    { id_state: "4", name: "Carmelo" },
    { id_state: "4", name: "Caserío El Cerro" },
    { id_state: "4", name: "Cerro Carmelo" },
    { id_state: "4", name: "Cerro De Las Armas" },
    { id_state: "4", name: "Cerros De San Juan" },
    { id_state: "4", name: "Cerros Negros" },
    { id_state: "4", name: "Chico Torino" },
    { id_state: "4", name: "Colonia Arrue" },
    { id_state: "4", name: "Colonia Cosmopolita" },
    { id_state: "4", name: "Colonia Del Sacramento" },
    { id_state: "4", name: "Colonia Española" },
    { id_state: "4", name: "Colonia Española Km. 109" },
    { id_state: "4", name: "Colonia Estrella" },
    { id_state: "4", name: "Colonia Peirano" },
    { id_state: "4", name: "Colonia Quevedo" },
    { id_state: "4", name: "Colonia Sarandí" },
    { id_state: "4", name: "Colonia Talice" },
    { id_state: "4", name: "Colonia Valdense" },
    { id_state: "4", name: "Conchillas" },
    { id_state: "4", name: "Concordia" },
    { id_state: "4", name: "Costa De Colla Al Este" },
    { id_state: "4", name: "Costa De Rosario" },
    { id_state: "4", name: "Costa De Tarariras" },
    { id_state: "4", name: "Costa De Vacas" },
    { id_state: "4", name: "Costa Del Navarro" },
    { id_state: "4", name: "Costas De Juan Gonzalez" },
    { id_state: "4", name: "Costas De Polonia" },
    { id_state: "4", name: "Costas De San Juan" },
    { id_state: "4", name: "Cufre" },
    { id_state: "4", name: "Curupi" },
    { id_state: "4", name: "El Bañado" },
    { id_state: "4", name: "El Caño" },
    { id_state: "4", name: "El Cerro" },
    { id_state: "4", name: "El Chileno" },
    { id_state: "4", name: "El Cuadro" },
    { id_state: "4", name: "El Ensueño" },
    { id_state: "4", name: "El Faro" },
    { id_state: "4", name: "El General" },
    { id_state: "4", name: "El Quinton" },
    { id_state: "4", name: "El Semillero" },
    { id_state: "4", name: "Estación Estanzuela" },
    { id_state: "4", name: "Estación Experimental 'la Estanzuela'" },
    { id_state: "4", name: "Florencio Sanchez" },
    { id_state: "4", name: "Fomento" },
    { id_state: "4", name: "Gil" },
    { id_state: "4", name: "Juan Carlos Caseros" },
    { id_state: "4", name: "Juan Gonzalez" },
    { id_state: "4", name: "Juan Jackson" },
    { id_state: "4", name: "Juan Lacaze" },
    { id_state: "4", name: "La Horqueta" },
    { id_state: "4", name: "La Paz" },
    { id_state: "4", name: "La Sierra" },
    { id_state: "4", name: "Laguna De Los Patos" },
    { id_state: "4", name: "Las Chispas" },
    { id_state: "4", name: "Las Flores" },
    { id_state: "4", name: "Lomas De Carmelo" },
    { id_state: "4", name: "Los Pinos" },
    { id_state: "4", name: "Manantiales" },
    { id_state: "4", name: "Martin Chico" },
    { id_state: "4", name: "Martin Chico De Conchillas" },
    { id_state: "4", name: "Media Agua" },
    { id_state: "4", name: "Miguelete" },
    { id_state: "4", name: "Miguelete De Conchillas" },
    { id_state: "4", name: "Minas De Narancio" },
    { id_state: "4", name: "Minuano Y Sauce" },
    { id_state: "4", name: "Molles De Miguelete" },
    { id_state: "4", name: "Nueva Helvecia" },
    { id_state: "4", name: "Nueva Palmira" },
    { id_state: "4", name: "Ombues De Lavalle" },
    { id_state: "4", name: "Paraje Minuano" },
    { id_state: "4", name: "Paso Antolin" },
    { id_state: "4", name: "Paso Birriel" },
    { id_state: "4", name: "Paso De La Quinta" },
    { id_state: "4", name: "Paso Hospital" },
    { id_state: "4", name: "Paso Hospital Manantiales" },
    { id_state: "4", name: "Paso Morlan" },
    { id_state: "4", name: "Paso Quicho" },
    { id_state: "4", name: "Pastoreo" },
    { id_state: "4", name: "Picada De Benitez" },
    { id_state: "4", name: "Piedra Chata" },
    { id_state: "4", name: "Piedra De Los Indios" },
    { id_state: "4", name: "Piedras Blancas" },
    { id_state: "4", name: "Playa Azul" },
    { id_state: "4", name: "Playa Britopolis" },
    { id_state: "4", name: "Playa Parant" },
    { id_state: "4", name: "Polancos" },
    { id_state: "4", name: "Puerto Concordia" },
    { id_state: "4", name: "Puerto Ingles" },
    { id_state: "4", name: "Puerto Platero" },
    { id_state: "4", name: "Puerto Rosario" },
    { id_state: "4", name: "Punta Francesa" },
    { id_state: "4", name: "Puntas De Juan Gonzalez" },
    { id_state: "4", name: "Puntas De Melo" },
    { id_state: "4", name: "Puntas De San Juan" },
    { id_state: "4", name: "Puntas De San Pedro" },
    { id_state: "4", name: "Puntas Del Riachuelo" },
    { id_state: "4", name: "Puntas Del Sauce" },
    { id_state: "4", name: "Quinton" },
    { id_state: "4", name: "Radial Hernandez" },
    { id_state: "4", name: "Radial Rosario" },
    { id_state: "4", name: "Real De Vera" },
    { id_state: "4", name: "Reducto" },
    { id_state: "4", name: "Resguardo Cufre" },
    { id_state: "4", name: "Riachuelo" },
    { id_state: "4", name: "Rincón Del Rey" },
    { id_state: "4", name: "Rosario" },
    { id_state: "4", name: "Rosario Y Colla" },
    { id_state: "4", name: "San Juan" },
    { id_state: "4", name: "San Luis" },
    { id_state: "4", name: "San Luis De Tarariras" },
    { id_state: "4", name: "San Luis Sanchez" },
    { id_state: "4", name: "San Pedro" },
    { id_state: "4", name: "San Pedro De Arriba" },
    { id_state: "4", name: "San Pedro Norte" },
    { id_state: "4", name: "San Roque" },
    { id_state: "4", name: "Santa Ana" },
    { id_state: "4", name: "Santa Regina" },
    { id_state: "4", name: "Santa Rosa" },
    { id_state: "4", name: "Sarandí Campana" },
    { id_state: "4", name: "Tarariras" },
    { id_state: "4", name: "Terminal" },
    { id_state: "4", name: "Tomas Bell" },
    { id_state: "4", name: "Tres Esquinas" },
    { id_state: "4", name: "Viboras" },
    { id_state: "4", name: "Viboras Y Vacas" },
    { id_state: "4", name: "Villa Pancha" },
    { id_state: "4", name: "Zagarzazu" },
    { id_state: "4", name: "Zunin" },
    { id_state: "5", name: "Abella" },
    { id_state: "5", name: "Aguas Buenas" },
    { id_state: "5", name: "Arroyo De Los Perros" },
    { id_state: "5", name: "Barrancas Coloradas" },
    { id_state: "5", name: "Batovi" },
    { id_state: "5", name: "Baygorria" },
    { id_state: "5", name: "Blanquillo" },
    { id_state: "5", name: "Blanquillo Al Oeste" },
    { id_state: "5", name: "Caballero" },
    { id_state: "5", name: "Capilla De Farruco" },
    { id_state: "5", name: "Carlos Reyles" },
    { id_state: "5", name: "Ceibal" },
    { id_state: "5", name: "Cerrezuelo" },
    { id_state: "5", name: "Cerro Convento" },
    { id_state: "5", name: "Chacras De Durazno" },
    { id_state: "5", name: "Chileno" },
    { id_state: "5", name: "Chileno Chico" },
    { id_state: "5", name: "Chileno Grande (aguero)" },
    { id_state: "5", name: "Costa De Cuadra" },
    { id_state: "5", name: "Cuchilla De Ramirez" },
    { id_state: "5", name: "Cuchilla Del Rincón" },
    { id_state: "5", name: "De Dios" },
    { id_state: "5", name: "Durazno" },
    { id_state: "5", name: "Elias Regules" },
    { id_state: "5", name: "Estación Chileno" },
    { id_state: "5", name: "Feliciano" },
    { id_state: "5", name: "Fonseca" },
    { id_state: "5", name: "Higueras De Carpinteria" },
    { id_state: "5", name: "La Alegria" },
    { id_state: "5", name: "La Mazamorra" },
    { id_state: "5", name: "La Paloma" },
    { id_state: "5", name: "Las Acacias" },
    { id_state: "5", name: "Las Cañas" },
    { id_state: "5", name: "Las Palmas" },
    { id_state: "5", name: "Las Tunas" },
    { id_state: "5", name: "Los Agregados" },
    { id_state: "5", name: "Los Tapes" },
    { id_state: "5", name: "Maestre Campo" },
    { id_state: "5", name: "Malbajar Este" },
    { id_state: "5", name: "Malbajar Oeste" },
    { id_state: "5", name: "Maria Cejas" },
    { id_state: "5", name: "Mariscala" },
    { id_state: "5", name: "Mariscala Del Carmen" },
    { id_state: "5", name: "Molles Chico" },
    { id_state: "5", name: "Molles De Quinteros" },
    { id_state: "5", name: "Mouriño" },
    { id_state: "5", name: "Municipio De Durazno" },
    { id_state: "5", name: "Ombues De Oribe" },
    { id_state: "5", name: "Palmar De Porrua" },
    { id_state: "5", name: "Parada Sur" },
    { id_state: "5", name: "Parish" },
    { id_state: "5", name: "Paso De Aguirre" },
    { id_state: "5", name: "Paso De Castro" },
    { id_state: "5", name: "Paso Del Medio Las Palmas" },
    { id_state: "5", name: "Paso Ramirez" },
    { id_state: "5", name: "Paso Real De Carpinteria" },
    { id_state: "5", name: "Paso Tejera" },
    { id_state: "5", name: "Pueblo Centenario" },
    { id_state: "5", name: "Pueblo De Alvarez" },
    { id_state: "5", name: "Puglia" },
    { id_state: "5", name: "Puntas De Carpinteria" },
    { id_state: "5", name: "Puntas De Herrera" },
    { id_state: "5", name: "Puntas De Malbajar" },
    { id_state: "5", name: "Rincón De Los Tapes" },
    { id_state: "5", name: "Rolon" },
    { id_state: "5", name: "Rossell Y Rius" },
    { id_state: "5", name: "Salinas" },
    { id_state: "5", name: "Salinas Chico" },
    { id_state: "5", name: "San Jorge" },
    { id_state: "5", name: "San José De Las Cañas" },
    { id_state: "5", name: "Sande Chico" },
    { id_state: "5", name: "Santa Bernardina" },
    { id_state: "5", name: "Sarandí De La China" },
    { id_state: "5", name: "Sarandí De Río Negro" },
    { id_state: "5", name: "Sarandí Del Yi" },
    { id_state: "5", name: "Sauce De Herrera" },
    { id_state: "5", name: "Sauce Del Yi" },
    { id_state: "5", name: "Tala De Mariscala" },
    { id_state: "5", name: "Tejera" },
    { id_state: "5", name: "Verdun" },
    { id_state: "5", name: "Villa Del Carmen" },
    { id_state: "5", name: "Villasboas" },
    { id_state: "6", name: "Ahogados" },
    { id_state: "6", name: "Andresito" },
    { id_state: "6", name: "Arenal Chico" },
    { id_state: "6", name: "Arenal Grande" },
    { id_state: "6", name: "Arroyo Malo" },
    { id_state: "6", name: "Cañada Amilivia" },
    { id_state: "6", name: "Cerro Colorado" },
    { id_state: "6", name: "Chacras" },
    { id_state: "6", name: "Chacras De Borghi" },
    { id_state: "6", name: "Colonia Alemana" },
    { id_state: "6", name: "Costas De San José" },
    { id_state: "6", name: "Costas Del Tala" },
    { id_state: "6", name: "Cuchilla De Villasboas" },
    { id_state: "6", name: "El Coronilla" },
    { id_state: "6", name: "El Totoral" },
    { id_state: "6", name: "Ferrizo" },
    { id_state: "6", name: "Ismael Cortinas" },
    { id_state: "6", name: "Juan José Castro" },
    { id_state: "6", name: "La Alianza" },
    { id_state: "6", name: "La Casilla" },
    { id_state: "6", name: "La Cordobesa" },
    { id_state: "6", name: "La Guardia" },
    { id_state: "6", name: "Marincho" },
    { id_state: "6", name: "Paso De Lugo" },
    { id_state: "6", name: "Paso Hondo" },
    { id_state: "6", name: "Pueblo Pintos" },
    { id_state: "6", name: "Puntas De Chamanga" },
    { id_state: "6", name: "Puntas De Marincho" },
    { id_state: "6", name: "Puntas De San José" },
    { id_state: "6", name: "Puntas De Sarandí" },
    { id_state: "6", name: "Puntas Del Corral De Piedra" },
    { id_state: "6", name: "Puntas Del Sauce" },
    { id_state: "6", name: "Rincón Del Palacio" },
    { id_state: "6", name: "San Gregorío De Flores" },
    { id_state: "6", name: "Santa Adelaida" },
    { id_state: "6", name: "Sarandí" },
    { id_state: "6", name: "Talas De Maciel" },
    { id_state: "6", name: "Trinidad" },
    { id_state: "6", name: "Villa Pastora" },
    { id_state: "6", name: "Villasboas" },
    { id_state: "7", name: "25 De Agosto" },
    { id_state: "7", name: "25 De Mayo" },
    { id_state: "7", name: "Alejandro Gallinal" },
    { id_state: "7", name: "Arrayan" },
    { id_state: "7", name: "Arroyo Chamizo" },
    { id_state: "7", name: "Arroyo De Los Negros" },
    { id_state: "7", name: "Arroyo Latorre" },
    { id_state: "7", name: "Arroyo Monzon" },
    { id_state: "7", name: "Arroyo Pelado" },
    { id_state: "7", name: "Arteaga" },
    { id_state: "7", name: "Barra Molles Del Timote" },
    { id_state: "7", name: "Barra Sauce De Mansavillagra" },
    { id_state: "7", name: "Berrondo" },
    { id_state: "7", name: "Calleri" },
    { id_state: "7", name: "Candil" },
    { id_state: "7", name: "Capilla Del Sauce" },
    { id_state: "7", name: "Cardal" },
    { id_state: "7", name: "Caserío La Fundacion" },
    { id_state: "7", name: "Casupa" },
    { id_state: "7", name: "Cerro Chato" },
    { id_state: "7", name: "Cerro De La Macana" },
    { id_state: "7", name: "Cerros De Florida" },
    { id_state: "7", name: "Chacras De Florida" },
    { id_state: "7", name: "Chacras Del Pintado" },
    { id_state: "7", name: "Chamizo" },
    { id_state: "7", name: "Chamizo Chico" },
    { id_state: "7", name: "Chilcas" },
    { id_state: "7", name: "Chingolas" },
    { id_state: "7", name: "Colonia Sanchez" },
    { id_state: "7", name: "Colonia Treinta Y Tres Orientales" },
    { id_state: "7", name: "Corral De Piedra" },
    { id_state: "7", name: "Costa De Arias" },
    { id_state: "7", name: "Costa De Illescas" },
    { id_state: "7", name: "Costa De La Cruz" },
    { id_state: "7", name: "Costa De Parana" },
    { id_state: "7", name: "Costa Del Tala" },
    { id_state: "7", name: "Costas De Arias" },
    { id_state: "7", name: "Costas De Chamizo" },
    { id_state: "7", name: "Costas De Chamizo Grande" },
    { id_state: "7", name: "Costas De Maciel" },
    { id_state: "7", name: "Costas De Santa Lucia Chico" },
    { id_state: "7", name: "Costas Del Amarillo" },
    { id_state: "7", name: "Costas Del Pintado" },
    { id_state: "7", name: "Costas Del Santa Lucia Grande" },
    { id_state: "7", name: "Cuchilla Santo Domingo" },
    { id_state: "7", name: "Dr. A. Gallinal" },
    { id_state: "7", name: "Estación Capilla Del Sauce" },
    { id_state: "7", name: "Ferrer" },
    { id_state: "7", name: "Florida" },
    { id_state: "7", name: "Fray Marcos" },
    { id_state: "7", name: "Goñi" },
    { id_state: "7", name: "Hernandarias" },
    { id_state: "7", name: "Independencia" },
    { id_state: "7", name: "Juncal" },
    { id_state: "7", name: "La Cimbra" },
    { id_state: "7", name: "La Cruz" },
    { id_state: "7", name: "La Escobilla" },
    { id_state: "7", name: "La Macana" },
    { id_state: "7", name: "La Palma" },
    { id_state: "7", name: "La Victoria" },
    { id_state: "7", name: "Las Piedritas" },
    { id_state: "7", name: "Mansavillagra" },
    { id_state: "7", name: "Mendoza" },
    { id_state: "7", name: "Mendoza Chico" },
    { id_state: "7", name: "Molles Del Pescado" },
    { id_state: "7", name: "Molles Del Timote" },
    { id_state: "7", name: "Montecoral" },
    { id_state: "7", name: "Nico Perez" },
    { id_state: "7", name: "Palermo" },
    { id_state: "7", name: "Pantanoso De Castro" },
    { id_state: "7", name: "Paso Calleros" },
    { id_state: "7", name: "Paso De Los Novillos" },
    { id_state: "7", name: "Paso Real De Mansavillagra" },
    { id_state: "7", name: "Paso Vela" },
    { id_state: "7", name: "Piedra Campana" },
    { id_state: "7", name: "Piedras Coloradas" },
    { id_state: "7", name: "Pintado" },
    { id_state: "7", name: "Polanco Del Yi" },
    { id_state: "7", name: "Pueblo De Los Morochos" },
    { id_state: "7", name: "Puente De Mendoza" },
    { id_state: "7", name: "Puntas De Calleros" },
    { id_state: "7", name: "Puntas De Chamame" },
    { id_state: "7", name: "Puntas De Chamizo" },
    { id_state: "7", name: "Puntas De Illescas" },
    { id_state: "7", name: "Puntas De La Escobilla" },
    { id_state: "7", name: "Puntas De Maciel" },
    { id_state: "7", name: "Puntas De Mansavillagra" },
    { id_state: "7", name: "Puntas De Sauce De Maciel" },
    { id_state: "7", name: "Puntas Del Arroyo Latorre" },
    { id_state: "7", name: "Reboledo" },
    { id_state: "7", name: "Rincón De Los Camilos" },
    { id_state: "7", name: "Rincón De Vignoli" },
    { id_state: "7", name: "Rincón Sauce Del Yi" },
    { id_state: "7", name: "San Gabriel" },
    { id_state: "7", name: "San Geronimo" },
    { id_state: "7", name: "San Juan" },
    { id_state: "7", name: "San Pedro De Timote" },
    { id_state: "7", name: "Santa Clara" },
    { id_state: "7", name: "Santa Teresa" },
    { id_state: "7", name: "Sarandí Grande" },
    { id_state: "7", name: "Sauce De Maciel" },
    { id_state: "7", name: "Sauce De Villanueva" },
    { id_state: "7", name: "Sauce Del Yi" },
    { id_state: "7", name: "Tabare" },
    { id_state: "7", name: "Tala De Castro" },
    { id_state: "7", name: "Tala De Maciel" },
    { id_state: "7", name: "Talita" },
    { id_state: "7", name: "Tornero" },
    { id_state: "7", name: "Uríoste" },
    { id_state: "7", name: "Valentines" },
    { id_state: "7", name: "Vignoli" },
    { id_state: "7", name: "Villa Hipica" },
    { id_state: "7", name: "Villa Vieja" },
    { id_state: "8", name: "19 De Junio" },
    { id_state: "8", name: "Abra De Zabaleta" },
    { id_state: "8", name: "Aguas Blancas" },
    { id_state: "8", name: "Aigua" },
    { id_state: "8", name: "Alonso" },
    { id_state: "8", name: "Andreoni" },
    { id_state: "8", name: "Aramendia" },
    { id_state: "8", name: "Arequita" },
    { id_state: "8", name: "Arroyo De Los Patos" },
    { id_state: "8", name: "Arroyo Del Medio" },
    { id_state: "8", name: "Azucar" },
    { id_state: "8", name: "Barra De Los Chanchos" },
    { id_state: "8", name: "Barrancas" },
    { id_state: "8", name: "Barriga Negra" },
    { id_state: "8", name: "Barrío La Coronilla - Ancap" },
    { id_state: "8", name: "Blanes Viale" },
    { id_state: "8", name: "Campanero" },
    { id_state: "8", name: "Canteras Del Verdun" },
    { id_state: "8", name: "Carnales" },
    { id_state: "8", name: "Casupa" },
    { id_state: "8", name: "Casupa Chico" },
    { id_state: "8", name: "Cerro Pelado" },
    { id_state: "8", name: "Chamame" },
    { id_state: "8", name: "Colón" },
    { id_state: "8", name: "Consejo Del Niño" },
    { id_state: "8", name: "Costa Del Lenguazo" },
    { id_state: "8", name: "Costas De Corrales" },
    { id_state: "8", name: "Costas Del Soldado" },
    { id_state: "8", name: "El Alto" },
    { id_state: "8", name: "El Perdido" },
    { id_state: "8", name: "El Soldado" },
    { id_state: "8", name: "El Tigre" },
    { id_state: "8", name: "Espuelitas" },
    { id_state: "8", name: "Estación Solís" },
    { id_state: "8", name: "Gaetan (cuchilla De Carbajal)" },
    { id_state: "8", name: "Godoy" },
    { id_state: "8", name: "Gutierrez" },
    { id_state: "8", name: "Higueritas" },
    { id_state: "8", name: "Illescas" },
    { id_state: "8", name: "José Batlle Y Ordoñez" },
    { id_state: "8", name: "José Pedro Varela" },
    { id_state: "8", name: "La Cuchilla" },
    { id_state: "8", name: "La Plata" },
    { id_state: "8", name: "Ladrillos" },
    { id_state: "8", name: "Larrosa" },
    { id_state: "8", name: "Las Achiras" },
    { id_state: "8", name: "Los Tapes" },
    { id_state: "8", name: "Manguera Azul" },
    { id_state: "8", name: "Marco De Los Reyes" },
    { id_state: "8", name: "Mariscala" },
    { id_state: "8", name: "Marmaraja" },
    { id_state: "8", name: "Minas" },
    { id_state: "8", name: "Molles De Aigua" },
    { id_state: "8", name: "Molles De Cañada Grande" },
    { id_state: "8", name: "Molles Del Sauce" },
    { id_state: "8", name: "Ombues De Bentancour" },
    { id_state: "8", name: "Ortiz" },
    { id_state: "8", name: "Ortiz Castro" },
    { id_state: "8", name: "Paso Arbelo" },
    { id_state: "8", name: "Paso De Los Troncos" },
    { id_state: "8", name: "Paso De Mesa" },
    { id_state: "8", name: "Piraraja" },
    { id_state: "8", name: "Polanco" },
    { id_state: "8", name: "Polanco Norte" },
    { id_state: "8", name: "Polanco Sur" },
    { id_state: "8", name: "Pororo" },
    { id_state: "8", name: "Puente De Marmaraja" },
    { id_state: "8", name: "Puntas De Barriga Negra" },
    { id_state: "8", name: "Puntas De Los Chanchos" },
    { id_state: "8", name: "Puntas De Polanco" },
    { id_state: "8", name: "Puntas De San Francisco" },
    { id_state: "8", name: "Puntas De Santa Lucia" },
    { id_state: "8", name: "Puntas De Solís" },
    { id_state: "8", name: "Puntas De Vejigas" },
    { id_state: "8", name: "Puntas Del Perdido" },
    { id_state: "8", name: "Retamosa" },
    { id_state: "8", name: "Rincón De Cebollati" },
    { id_state: "8", name: "Rincón De Mariscala" },
    { id_state: "8", name: "Rincón De Silva" },
    { id_state: "8", name: "Roldan" },
    { id_state: "8", name: "San Francisco De Las Sierras" },
    { id_state: "8", name: "Santa Lucia" },
    { id_state: "8", name: "Sarandí De Gutierrez" },
    { id_state: "8", name: "Sauce De Aigua" },
    { id_state: "8", name: "Sauce De Olimar Chico" },
    { id_state: "8", name: "Sierras Blancas" },
    { id_state: "8", name: "Soldado" },
    { id_state: "8", name: "Solís" },
    { id_state: "8", name: "Solís De Mataojo" },
    { id_state: "8", name: "Solís Grande" },
    { id_state: "8", name: "Tapes Chico" },
    { id_state: "8", name: "Tapes Grande" },
    { id_state: "8", name: "Valle De Solís" },
    { id_state: "8", name: "Vejigas" },
    { id_state: "8", name: "Velazquez" },
    { id_state: "8", name: "Verdun" },
    { id_state: "8", name: "Villa Del Rosario" },
    { id_state: "8", name: "Villa Serrana" },
    { id_state: "8", name: "Zapican" },
    { id_state: "9", name: "Abra De Castellanos" },
    { id_state: "9", name: "Abra De Perdomo" },
    { id_state: "9", name: "Aiguá" },
    { id_state: "9", name: "Alfaro" },
    { id_state: "9", name: "Alferez" },
    { id_state: "9", name: "Arenas De José Ignacio" },
    { id_state: "9", name: "Arroyito De Medina" },
    { id_state: "9", name: "Balnearío Buenos Aires" },
    { id_state: "9", name: "Barra De Portezuelo" },
    { id_state: "9", name: "Barra Del Sauce" },
    { id_state: "9", name: "Bella Vista" },
    { id_state: "9", name: "Buenos Aires" },
    { id_state: "9", name: "Cañada Bellaca" },
    { id_state: "9", name: "Cañada De La Cruz" },
    { id_state: "9", name: "Canteras De Marelli" },
    { id_state: "9", name: "Carape" },
    { id_state: "9", name: "Carlos Cal" },
    { id_state: "9", name: "Cerro Pelado" },
    { id_state: "9", name: "Cerros Azules" },
    { id_state: "9", name: "Chihuahua" },
    { id_state: "9", name: "Colonia J. Suarez" },
    { id_state: "9", name: "Coronilla" },
    { id_state: "9", name: "Corte De La Leña" },
    { id_state: "9", name: "Costas De José Ignacio" },
    { id_state: "9", name: "Eden Rock" },
    { id_state: "9", name: "El Chorro" },
    { id_state: "9", name: "El Eden" },
    { id_state: "9", name: "El Quijote" },
    { id_state: "9", name: "El Tesoro" },
    { id_state: "9", name: "Faro José Ignacio" },
    { id_state: "9", name: "Faro José Ignacio Norte" },
    { id_state: "9", name: "Garzon" },
    { id_state: "9", name: "Gerona" },
    { id_state: "9", name: "Gregorío Aznarez" },
    { id_state: "9", name: "Guardia Vieja" },
    { id_state: "9", name: "José Ignacio" },
    { id_state: "9", name: "La Barra" },
    { id_state: "9", name: "La Capuera" },
    { id_state: "9", name: "La Falda" },
    { id_state: "9", name: "La Juanita" },
    { id_state: "9", name: "La Sierra" },
    { id_state: "9", name: "La Sonrisa" },
    { id_state: "9", name: "Lago De Los Cisnes" },
    { id_state: "9", name: "Laguna Blanca" },
    { id_state: "9", name: "Laguna Del Sauce" },
    { id_state: "9", name: "Las Cañas" },
    { id_state: "9", name: "Las Cumbres" },
    { id_state: "9", name: "Las Flores" },
    { id_state: "9", name: "Las Flores - Estación" },
    { id_state: "9", name: "Los Aromos" },
    { id_state: "9", name: "Los Ceibos" },
    { id_state: "9", name: "Los Corchos" },
    { id_state: "9", name: "Los Talas" },
    { id_state: "9", name: "Maldonado" },
    { id_state: "9", name: "Manantiales" },
    { id_state: "9", name: "Mataojo" },
    { id_state: "9", name: "Molles De Garzon" },
    { id_state: "9", name: "Nueva Carrara" },
    { id_state: "9", name: "Ocean Park" },
    { id_state: "9", name: "Pago De La Paja" },
    { id_state: "9", name: "Pan De Azucar" },
    { id_state: "9", name: "Parque Medina" },
    { id_state: "9", name: "Partido Norte" },
    { id_state: "9", name: "Partido Oeste" },
    { id_state: "9", name: "Paso De La Cantera" },
    { id_state: "9", name: "Paso De Los Talas" },
    { id_state: "9", name: "Pinares - Las Delicias" },
    { id_state: "9", name: "Piriapolis" },
    { id_state: "9", name: "Playa Grande" },
    { id_state: "9", name: "Playa Hermosa" },
    { id_state: "9", name: "Playa Verde" },
    { id_state: "9", name: "Portezuelo" },
    { id_state: "9", name: "Pueblo Solís" },
    { id_state: "9", name: "Punta Ballena" },
    { id_state: "9", name: "Punta Colorada" },
    { id_state: "9", name: "Punta Del Este" },
    { id_state: "9", name: "Punta Fria" },
    { id_state: "9", name: "Punta Negra" },
    { id_state: "9", name: "Puntas De José Ignacio" },
    { id_state: "9", name: "Puntas De La Sierra" },
    { id_state: "9", name: "Puntas De Mataojo" },
    { id_state: "9", name: "Puntas De Pan De Azucar" },
    { id_state: "9", name: "Puntas Del Campanera" },
    { id_state: "9", name: "Rincón De Aparicio" },
    { id_state: "9", name: "Rincón De Los Sosa" },
    { id_state: "9", name: "Rincón Del Indio" },
    { id_state: "9", name: "Ruta 37 Y 9" },
    { id_state: "9", name: "Salamanca" },
    { id_state: "9", name: "San Carlos" },
    { id_state: "9", name: "San Juan Del Este" },
    { id_state: "9", name: "San Rafael El Placer" },
    { id_state: "9", name: "San Vicente" },
    { id_state: "9", name: "Santa Monica" },
    { id_state: "9", name: "Sarandí De Aigua" },
    { id_state: "9", name: "Sarandí Del Mataojo" },
    { id_state: "9", name: "Sauce De Aigua" },
    { id_state: "9", name: "Sauce De Portezuelo" },
    { id_state: "9", name: "Solís" },
    { id_state: "9", name: "Valdivia" },
    { id_state: "9", name: "Villa Delia" },
    { id_state: "9", name: "Zanja Del Tigre" },
    { id_state: "10", name: "Melilla" },
    { id_state: "10", name: "Montevideo" },
    { id_state: "10", name: "Santiago Vazquez" },
    { id_state: "11", name: "Al Sur De Arroyo Sacra" },
    { id_state: "11", name: "Araujo" },
    { id_state: "11", name: "Arroyo Malo" },
    { id_state: "11", name: "Arroyo Negro" },
    { id_state: "11", name: "Beisso" },
    { id_state: "11", name: "Bella Vista" },
    { id_state: "11", name: "Cañada Del Pueblo" },
    { id_state: "11", name: "Cangue" },
    { id_state: "11", name: "Carumbe" },
    { id_state: "11", name: "Casablanca" },
    { id_state: "11", name: "Cerro Chato" },
    { id_state: "11", name: "Chacras De Paysandú" },
    { id_state: "11", name: "Chacras De Paysandú Norte" },
    { id_state: "11", name: "Chacras De Paysandú Sur" },
    { id_state: "11", name: "Chapicuy" },
    { id_state: "11", name: "Colonia Arroyo Malo" },
    { id_state: "11", name: "Colonia Cangue" },
    { id_state: "11", name: "Colonia Juncal" },
    { id_state: "11", name: "Colonia Las Delicias" },
    { id_state: "11", name: "Colonia Paysandú" },
    { id_state: "11", name: "Colonia Santa Blanca" },
    { id_state: "11", name: "Colonia Uruguaya" },
    { id_state: "11", name: "Constancia" },
    { id_state: "11", name: "Costa De Sacra" },
    { id_state: "11", name: "Cuchilla De Buricayupi" },
    { id_state: "11", name: "Cuchilla De Fuego" },
    { id_state: "11", name: "Cuchilla San José" },
    { id_state: "11", name: "Dayman (parada Dayman)" },
    { id_state: "11", name: "El Chaco" },
    { id_state: "11", name: "El Duraznal" },
    { id_state: "11", name: "El Eucaliptus" },
    { id_state: "11", name: "El Horno" },
    { id_state: "11", name: "El Tarugo" },
    { id_state: "11", name: "Esperanza" },
    { id_state: "11", name: "Estación Porvenir" },
    { id_state: "11", name: "Etchemendi" },
    { id_state: "11", name: "Gallinal" },
    { id_state: "11", name: "Guaviyu De Quebracho" },
    { id_state: "11", name: "Guayabos" },
    { id_state: "11", name: "Guichon" },
    { id_state: "11", name: "La Lata Ruta 3 (km. 375)" },
    { id_state: "11", name: "La Paz (ruta 3 Km. 346)" },
    { id_state: "11", name: "La Tentacion" },
    { id_state: "11", name: "Las Flores" },
    { id_state: "11", name: "Las Palmas" },
    { id_state: "11", name: "Lorenzo Geyres" },
    { id_state: "11", name: "Molles Grande" },
    { id_state: "11", name: "Morato (tres árboles)" },
    { id_state: "11", name: "Nuevo Paysandú" },
    { id_state: "11", name: "Orgoroso" },
    { id_state: "11", name: "Palmar Del Quebracho" },
    { id_state: "11", name: "Pandule" },
    { id_state: "11", name: "Parada Rivas" },
    { id_state: "11", name: "Paso De Los Carros" },
    { id_state: "11", name: "Paysandú" },
    { id_state: "11", name: "Perico Moreno" },
    { id_state: "11", name: "Piedra Sola" },
    { id_state: "11", name: "Piedras Coloradas" },
    { id_state: "11", name: "Piñera" },
    { id_state: "11", name: "Porvenir" },
    { id_state: "11", name: "Pueblo Alonzo" },
    { id_state: "11", name: "Pueblo Federacion" },
    { id_state: "11", name: "Puntas De Arroyo Negro" },
    { id_state: "11", name: "Puntas De Bacacua" },
    { id_state: "11", name: "Puntas De Buricayupi" },
    { id_state: "11", name: "Puntas De Cangue" },
    { id_state: "11", name: "Puntas De Gualeguay" },
    { id_state: "11", name: "Puntas De Las Isletas" },
    { id_state: "11", name: "Quebracho" },
    { id_state: "11", name: "Queguay Grande" },
    { id_state: "11", name: "Queguayar" },
    { id_state: "11", name: "Rabon" },
    { id_state: "11", name: "San Felix" },
    { id_state: "11", name: "San Francisco" },
    { id_state: "11", name: "San Mauricio" },
    { id_state: "11", name: "San Miguel" },
    { id_state: "11", name: "Santa Kilda" },
    { id_state: "11", name: "Sauce De Abajo" },
    { id_state: "11", name: "Sauce Del Buricayupi" },
    { id_state: "11", name: "Sauce Del Queguay" },
    { id_state: "11", name: "Soto" },
    { id_state: "11", name: "Tambores" },
    { id_state: "11", name: "Termas De Almiron" },
    { id_state: "11", name: "Termas De Guaviyu" },
    { id_state: "11", name: "Tomas Paz" },
    { id_state: "11", name: "Totoral" },
    { id_state: "11", name: "Tres Bocas" },
    { id_state: "11", name: "Valdez" },
    { id_state: "11", name: "Villa Maria (tiatucura)" },
    { id_state: "11", name: "Zeballos" },
    { id_state: "12", name: "Algorta" },
    { id_state: "12", name: "Arroyo Negro" },
    { id_state: "12", name: "Barrío Anglo" },
    { id_state: "12", name: "Bellaco" },
    { id_state: "12", name: "Cañitas" },
    { id_state: "12", name: "Caracoles" },
    { id_state: "12", name: "Don Esteban" },
    { id_state: "12", name: "El Abrojal" },
    { id_state: "12", name: "El Ombu" },
    { id_state: "12", name: "El Progreso" },
    { id_state: "12", name: "El Surco" },
    { id_state: "12", name: "Estación Francia" },
    { id_state: "12", name: "Estancia Vichadero" },
    { id_state: "12", name: "Fray Bentos" },
    { id_state: "12", name: "Grecco" },
    { id_state: "12", name: "Isla De Arguelles" },
    { id_state: "12", name: "La Arena" },
    { id_state: "12", name: "La Coronilla" },
    { id_state: "12", name: "La Florida" },
    { id_state: "12", name: "La Palma" },
    { id_state: "12", name: "La Union" },
    { id_state: "12", name: "Las Cañas" },
    { id_state: "12", name: "Las Flores" },
    { id_state: "12", name: "Las Fracciones" },
    { id_state: "12", name: "Las Margaritas" },
    { id_state: "12", name: "Los Arrayanes" },
    { id_state: "12", name: "Los Mellizos" },
    { id_state: "12", name: "Los Ranchos" },
    { id_state: "12", name: "Mataojo" },
    { id_state: "12", name: "Menafra" },
    { id_state: "12", name: "Merinos" },
    { id_state: "12", name: "Molles De Porrua" },
    { id_state: "12", name: "Nuevo Berlin" },
    { id_state: "12", name: "Ombucitos" },
    { id_state: "12", name: "Palmar Grande" },
    { id_state: "12", name: "Paso De Balbuena" },
    { id_state: "12", name: "Paso De Leopoldo" },
    { id_state: "12", name: "Paso De Los Cobres" },
    { id_state: "12", name: "Paso De Soca" },
    { id_state: "12", name: "Paso Ramirez" },
    { id_state: "12", name: "Pauru" },
    { id_state: "12", name: "Porton Haedo" },
    { id_state: "12", name: "Pte. San Martin" },
    { id_state: "12", name: "Puntas De Averías" },
    { id_state: "12", name: "Rolon" },
    { id_state: "12", name: "San Javier" },
    { id_state: "12", name: "San Lorenzo" },
    { id_state: "12", name: "Sanchez" },
    { id_state: "12", name: "Sanchez Chico" },
    { id_state: "12", name: "Santa Elisa" },
    { id_state: "12", name: "Santa Isabel" },
    { id_state: "12", name: "Santa Rosa" },
    { id_state: "12", name: "Sarandí" },
    { id_state: "12", name: "Sarandí De Navarro" },
    { id_state: "12", name: "Sauce" },
    { id_state: "12", name: "Tres Bocas" },
    { id_state: "12", name: "Tres Quintas" },
    { id_state: "12", name: "Uleste" },
    { id_state: "12", name: "Valle De Soba" },
    { id_state: "12", name: "Villa General Borges" },
    { id_state: "12", name: "Villa Maria" },
    { id_state: "12", name: "Yaguarete" },
    { id_state: "12", name: "Young" },
    { id_state: "13", name: "Abrojal" },
    { id_state: "13", name: "Alborada" },
    { id_state: "13", name: "Amarillo" },
    { id_state: "13", name: "Arroyo Blanco" },
    { id_state: "13", name: "Arroyo Sauzal" },
    { id_state: "13", name: "Ataques" },
    { id_state: "13", name: "Bañado Del Chaja" },
    { id_state: "13", name: "Barra De Ataques" },
    { id_state: "13", name: "Batovi" },
    { id_state: "13", name: "Berruti" },
    { id_state: "13", name: "Blanquillos" },
    { id_state: "13", name: "Buena Orden Al Norte" },
    { id_state: "13", name: "Buena Union" },
    { id_state: "13", name: "Capon Alto" },
    { id_state: "13", name: "Caraguata" },
    { id_state: "13", name: "Carpinteria" },
    { id_state: "13", name: "Cerrillada" },
    { id_state: "13", name: "Cerro Alegre" },
    { id_state: "13", name: "Cerro Blanco De Cuñapiru" },
    { id_state: "13", name: "Cerro Caqueiro" },
    { id_state: "13", name: "Cerro Chapeu" },
    { id_state: "13", name: "Cerro Chato" },
    { id_state: "13", name: "Cerro Pelado" },
    { id_state: "13", name: "Cerro Pelado Al Este" },
    { id_state: "13", name: "Cerro Solito" },
    { id_state: "13", name: "Cerros Blancos" },
    { id_state: "13", name: "Cerros De La Calera" },
    { id_state: "13", name: "Chirca De Caraguata" },
    { id_state: "13", name: "Coronilla" },
    { id_state: "13", name: "Coronilla De Corrales" },
    { id_state: "13", name: "Costas De Cuñapiru" },
    { id_state: "13", name: "Cruz De San Pedro" },
    { id_state: "13", name: "Cuchilla De Tres Cerros" },
    { id_state: "13", name: "Cuchilla De Yaguari" },
    { id_state: "13", name: "Cuchilla Mangueras" },
    { id_state: "13", name: "Cuñapiru" },
    { id_state: "13", name: "Curticeiras" },
    { id_state: "13", name: "Curtume" },
    { id_state: "13", name: "El Ceibo" },
    { id_state: "13", name: "El Palmito" },
    { id_state: "13", name: "Guaviyu" },
    { id_state: "13", name: "Hospital" },
    { id_state: "13", name: "La Caillava" },
    { id_state: "13", name: "La Calera" },
    { id_state: "13", name: "La Cerrillada" },
    { id_state: "13", name: "La Chilca" },
    { id_state: "13", name: "La Palma" },
    { id_state: "13", name: "La Pedrera" },
    { id_state: "13", name: "Lagos Del Norte" },
    { id_state: "13", name: "Lagunon" },
    { id_state: "13", name: "Lapuente" },
    { id_state: "13", name: "Las Flores" },
    { id_state: "13", name: "Laureles" },
    { id_state: "13", name: "Los Potreros" },
    { id_state: "13", name: "Lunarejo" },
    { id_state: "13", name: "Mandubi" },
    { id_state: "13", name: "Manuel Diaz" },
    { id_state: "13", name: "Masoller" },
    { id_state: "13", name: "Minas De Corrales" },
    { id_state: "13", name: "Minas De Cuñapiru (usinas)" },
    { id_state: "13", name: "Minas De Zapucay" },
    { id_state: "13", name: "Moirones" },
    { id_state: "13", name: "Parada Medina" },
    { id_state: "13", name: "Paso Amarillo" },
    { id_state: "13", name: "Paso Ataques" },
    { id_state: "13", name: "Paso De Arriera" },
    { id_state: "13", name: "Paso De Ataques" },
    { id_state: "13", name: "Paso De Frontera" },
    { id_state: "13", name: "Paso De Gaire" },
    { id_state: "13", name: "Paso De La Arena" },
    { id_state: "13", name: "Paso De La Calera" },
    { id_state: "13", name: "Paso Del Lagunon" },
    { id_state: "13", name: "Paso Del Puerto" },
    { id_state: "13", name: "Paso Del Tapado" },
    { id_state: "13", name: "Paso Serpa" },
    { id_state: "13", name: "Piedras Blancas" },
    { id_state: "13", name: "Platon" },
    { id_state: "13", name: "Pueblo De Los Santos" },
    { id_state: "13", name: "Pueblo Socorro" },
    { id_state: "13", name: "Puntas De Abrojal" },
    { id_state: "13", name: "Puntas De Corrales" },
    { id_state: "13", name: "Puntas De Cuñapiru" },
    { id_state: "13", name: "Puntas Del Sauzal" },
    { id_state: "13", name: "Puntas Del Yaguari" },
    { id_state: "13", name: "Rincón De Amarillo" },
    { id_state: "13", name: "Rincón De Diniz" },
    { id_state: "13", name: "Rincón De Los Castillos" },
    { id_state: "13", name: "Rincón De Moraes" },
    { id_state: "13", name: "Rincón De Rodriguez" },
    { id_state: "13", name: "Rincón De Roland" },
    { id_state: "13", name: "Rincón De Tres Cerros" },
    { id_state: "13", name: "Rincón De Yaguari" },
    { id_state: "13", name: "Rivera" },
    { id_state: "13", name: "San Gregorío" },
    { id_state: "13", name: "Santa Ernestina" },
    { id_state: "13", name: "Santa Isabel" },
    { id_state: "13", name: "Santa Teresa" },
    { id_state: "13", name: "Sauce De Batovi" },
    { id_state: "13", name: "Sauzal" },
    { id_state: "13", name: "Segarra" },
    { id_state: "13", name: "Tranqueras" },
    { id_state: "13", name: "Tres Cerros" },
    { id_state: "13", name: "Tres Cruces" },
    { id_state: "13", name: "Tres Puentes" },
    { id_state: "13", name: "Vichadero" },
    { id_state: "13", name: "Villa Indart" },
    { id_state: "13", name: "Yaguari" },
    { id_state: "13", name: "Zanja Honda" },
    { id_state: "13", name: "Zanja Honda De Tranqueras" },
    { id_state: "14", name: "18 De Julio" },
    { id_state: "14", name: "19 De Abril" },
    { id_state: "14", name: "Abra De Alferez" },
    { id_state: "14", name: "Aguas Dulces" },
    { id_state: "14", name: "Alferez" },
    { id_state: "14", name: "Antoniopolis" },
    { id_state: "14", name: "Arachania" },
    { id_state: "14", name: "Arbolito" },
    { id_state: "14", name: "Balnearío Pueblo Nuevo" },
    { id_state: "14", name: "Barra De Valizas" },
    { id_state: "14", name: "Barra Del Chuy" },
    { id_state: "14", name: "Barra Isla Negra" },
    { id_state: "14", name: "Barrancas De La Coronilla" },
    { id_state: "14", name: "Barrío Cardozo" },
    { id_state: "14", name: "Barrío Carpacho" },
    { id_state: "14", name: "Barrío Pereira" },
    { id_state: "14", name: "Barrío Porvenir" },
    { id_state: "14", name: "Barrío Torres" },
    { id_state: "14", name: "Cabo Polonio" },
    { id_state: "14", name: "Capacho" },
    { id_state: "14", name: "Castillos" },
    { id_state: "14", name: "Cebollati" },
    { id_state: "14", name: "Cerro De Los Rocha" },
    { id_state: "14", name: "Cerro De Pescadores" },
    { id_state: "14", name: "Chuy" },
    { id_state: "14", name: "Colonia Greissing" },
    { id_state: "14", name: "Costas De Cebollati" },
    { id_state: "14", name: "Cuchilla De Garzon" },
    { id_state: "14", name: "Cuchilla Del Arbolito" },
    { id_state: "14", name: "El Canelon" },
    { id_state: "14", name: "El Chimango" },
    { id_state: "14", name: "Empalme De Velazquez" },
    { id_state: "14", name: "Garzon Abajo" },
    { id_state: "14", name: "Garzon Al Medio" },
    { id_state: "14", name: "Garzon Arriba" },
    { id_state: "14", name: "India Muerta" },
    { id_state: "14", name: "Isla Negra" },
    { id_state: "14", name: "Kilometro 18" },
    { id_state: "14", name: "La Aguada Y Costa Azul" },
    { id_state: "14", name: "La Centinela" },
    { id_state: "14", name: "La Coronilla" },
    { id_state: "14", name: "La Esmeralda" },
    { id_state: "14", name: "La Fortaleza De Santa Teresa" },
    { id_state: "14", name: "La Paloma" },
    { id_state: "14", name: "La Pedrera" },
    { id_state: "14", name: "La Ribiera" },
    { id_state: "14", name: "La Sierra" },
    { id_state: "14", name: "La Tuna" },
    { id_state: "14", name: "Lascano" },
    { id_state: "14", name: "Lomas" },
    { id_state: "14", name: "Los Ajos" },
    { id_state: "14", name: "Los Cerrillos" },
    { id_state: "14", name: "Los Indios" },
    { id_state: "14", name: "Oceania Del Polonio" },
    { id_state: "14", name: "Oratorío" },
    { id_state: "14", name: "Palmar" },
    { id_state: "14", name: "Palmar De Castillos" },
    { id_state: "14", name: "Palmares De La Coronilla" },
    { id_state: "14", name: "Paralle" },
    { id_state: "14", name: "Paso De Lopez" },
    { id_state: "14", name: "Paso Del Bañado" },
    { id_state: "14", name: "Paso Del Ombu" },
    { id_state: "14", name: "Paso Doña Rosa" },
    { id_state: "14", name: "Picada Tolosa" },
    { id_state: "14", name: "Plano 291" },
    { id_state: "14", name: "Pueblo Nuevo" },
    { id_state: "14", name: "Puente Valizas" },
    { id_state: "14", name: "Puerto De Los Botes" },
    { id_state: "14", name: "Puimayen" },
    { id_state: "14", name: "Punta Cebollati" },
    { id_state: "14", name: "Punta Del Diablo" },
    { id_state: "14", name: "Punta Palmar" },
    { id_state: "14", name: "Punta Rubia" },
    { id_state: "14", name: "Puntas De Don Carlos" },
    { id_state: "14", name: "Quebracho" },
    { id_state: "14", name: "Rincón De Los Olivera" },
    { id_state: "14", name: "Rincón De Valizas" },
    { id_state: "14", name: "Rocha" },
    { id_state: "14", name: "Samuel" },
    { id_state: "14", name: "San Antonio" },
    { id_state: "14", name: "San Luis Al Medio" },
    { id_state: "14", name: "San Sebastian" },
    { id_state: "14", name: "San Sebastian De La Pedrera" },
    { id_state: "14", name: "Sarandí De La India Muerta" },
    { id_state: "14", name: "Sauce De Rocha" },
    { id_state: "14", name: "Sierra De Los Rocha" },
    { id_state: "14", name: "Tajamares De La Pedrera" },
    { id_state: "14", name: "Velazquez" },
    { id_state: "14", name: "Vuelta Del Palmar" },
    { id_state: "15", name: "Albisu" },
    { id_state: "15", name: "Arenitas Blancas" },
    { id_state: "15", name: "Barrío Hipodromo" },
    { id_state: "15", name: "Belen" },
    { id_state: "15", name: "Biassini" },
    { id_state: "15", name: "Bordenave" },
    { id_state: "15", name: "Campo De Todos" },
    { id_state: "15", name: "Carumbe" },
    { id_state: "15", name: "Cayetano" },
    { id_state: "15", name: "Celeste" },
    { id_state: "15", name: "Cerrillada" },
    { id_state: "15", name: "Cerrilladas De Saucedo" },
    { id_state: "15", name: "Cerro Chato" },
    { id_state: "15", name: "Cerros De Vera" },
    { id_state: "15", name: "Chacras De Constitucion" },
    { id_state: "15", name: "Colonia 18 De Julio" },
    { id_state: "15", name: "Colonia Itapebi" },
    { id_state: "15", name: "Colonia Osimani" },
    { id_state: "15", name: "Colonia Rubio" },
    { id_state: "15", name: "Constitucion" },
    { id_state: "15", name: "Corral De Piedra" },
    { id_state: "15", name: "Corralito" },
    { id_state: "15", name: "Cuchilla De Guaviyu" },
    { id_state: "15", name: "Cuchilla Del Salto" },
    { id_state: "15", name: "El Espinillar" },
    { id_state: "15", name: "El Mellado" },
    { id_state: "15", name: "Ferreira" },
    { id_state: "15", name: "Garibaldi" },
    { id_state: "15", name: "Guaviyu De Arapey" },
    { id_state: "15", name: "Itapebi" },
    { id_state: "15", name: "La Bolsa" },
    { id_state: "15", name: "La Bolsa 02" },
    { id_state: "15", name: "La Bolsa 03" },
    { id_state: "15", name: "La Viticola" },
    { id_state: "15", name: "Las Flores" },
    { id_state: "15", name: "Laureles" },
    { id_state: "15", name: "Lavalleja" },
    { id_state: "15", name: "Lluveras" },
    { id_state: "15", name: "Los Orientales" },
    { id_state: "15", name: "Mataojito" },
    { id_state: "15", name: "Mataojo" },
    { id_state: "15", name: "Mataojo Grande" },
    { id_state: "15", name: "Nueva Hesperides" },
    { id_state: "15", name: "Olivera" },
    { id_state: "15", name: "Osimani Y Llerena" },
    { id_state: "15", name: "Palomas" },
    { id_state: "15", name: "Parada Herreria" },
    { id_state: "15", name: "Parque José Luis" },
    { id_state: "15", name: "Paso Cementerío" },
    { id_state: "15", name: "Paso De Las Piedras De Arerungua" },
    { id_state: "15", name: "Paso Del Parque Del Dayman" },
    { id_state: "15", name: "Paso Del Potrero" },
    { id_state: "15", name: "Paso Del Tapado" },
    { id_state: "15", name: "Paso Fialho" },
    { id_state: "15", name: "Paso Nuevo Del Arapey" },
    { id_state: "15", name: "Paso Valega" },
    { id_state: "15", name: "Pepe Nuñez" },
    { id_state: "15", name: "Pueblo Farías" },
    { id_state: "15", name: "Puntas De Valentin" },
    { id_state: "15", name: "Quintana" },
    { id_state: "15", name: "Rincón De Valentin" },
    { id_state: "15", name: "Russo" },
    { id_state: "15", name: "Salto" },
    { id_state: "15", name: "San Antonio" },
    { id_state: "15", name: "Sarandí De Arapey" },
    { id_state: "15", name: "Sauce Chico" },
    { id_state: "15", name: "Saucedo" },
    { id_state: "15", name: "Talas De Itapebi" },
    { id_state: "15", name: "Termas Del Arapey" },
    { id_state: "15", name: "Termas Del Dayman" },
    { id_state: "15", name: "Toro Negro" },
    { id_state: "15", name: "Tropezon" },
    { id_state: "15", name: "Tropiezo" },
    { id_state: "15", name: "Valentin Grande" },
    { id_state: "15", name: "Zanja De Alcain" },
    { id_state: "15", name: "Zanja Del Tigre" },
    { id_state: "16", name: "18 De Julio" },
    { id_state: "16", name: "Arroyo De La Virgen" },
    { id_state: "16", name: "Arroyo Llano" },
    { id_state: "16", name: "Autodromo Nacional" },
    { id_state: "16", name: "Bañado" },
    { id_state: "16", name: "Bella Vista" },
    { id_state: "16", name: "Boca Del Cufre" },
    { id_state: "16", name: "Cagancha" },
    { id_state: "16", name: "Cagancha Chico" },
    { id_state: "16", name: "Cañada Grande" },
    { id_state: "16", name: "Capurro" },
    { id_state: "16", name: "Carreta Quemada" },
    { id_state: "16", name: "Ceramicas Del Sur" },
    { id_state: "16", name: "Chamizo" },
    { id_state: "16", name: "Ciudad Del Plata" },
    { id_state: "16", name: "Cololo Tinosa" },
    { id_state: "16", name: "Colonia America" },
    { id_state: "16", name: "Colonia Delta" },
    { id_state: "16", name: "Colonia Dr. Bernardo Etchepare" },
    { id_state: "16", name: "Colonia Fernandez Crespo" },
    { id_state: "16", name: "Colonia Italia" },
    { id_state: "16", name: "Colonia Juan Maria Perez" },
    { id_state: "16", name: "Colonia San Joaquín" },
    { id_state: "16", name: "Colonia Wilson" },
    { id_state: "16", name: "Coronilla" },
    { id_state: "16", name: "Costa Del Mauricio" },
    { id_state: "16", name: "Costas De Pereira" },
    { id_state: "16", name: "Costas Del Sauce" },
    { id_state: "16", name: "Cruz De Los Caminos" },
    { id_state: "16", name: "Cuchilla De Pereira" },
    { id_state: "16", name: "Cuchilla Del Vichadero" },
    { id_state: "16", name: "Cuchilla Seca" },
    { id_state: "16", name: "Delta El Tigre" },
    { id_state: "16", name: "Ecilda Paullier" },
    { id_state: "16", name: "Escudero" },
    { id_state: "16", name: "Fajardo" },
    { id_state: "16", name: "Fajina" },
    { id_state: "16", name: "Gonzalez" },
    { id_state: "16", name: "Guaycuru" },
    { id_state: "16", name: "Ituzaingo" },
    { id_state: "16", name: "Jesus Maria" },
    { id_state: "16", name: "Juan Soler" },
    { id_state: "16", name: "Juncal" },
    { id_state: "16", name: "Kiyu-ordeig" },
    { id_state: "16", name: "La Boyada" },
    { id_state: "16", name: "La Casilla" },
    { id_state: "16", name: "La Cuchilla" },
    { id_state: "16", name: "Laurel" },
    { id_state: "16", name: "Libertad" },
    { id_state: "16", name: "Mahoma" },
    { id_state: "16", name: "Mal Abrigo" },
    { id_state: "16", name: "Mangrullo" },
    { id_state: "16", name: "Monte Grande" },
    { id_state: "16", name: "Mundo Azul" },
    { id_state: "16", name: "Mundo Azul Aguirre" },
    { id_state: "16", name: "Orillas Del Plata" },
    { id_state: "16", name: "Pachina" },
    { id_state: "16", name: "Panta" },
    { id_state: "16", name: "Pantanoso" },
    { id_state: "16", name: "Parque Postel" },
    { id_state: "16", name: "Parque Postel Cnel. Adrian Medina" },
    { id_state: "16", name: "Paso Belastiqui" },
    { id_state: "16", name: "Paso De Cames" },
    { id_state: "16", name: "Paso De Las Piedras" },
    { id_state: "16", name: "Paso De Mas" },
    { id_state: "16", name: "Paso Del Carreton" },
    { id_state: "16", name: "Paso Del Guaycuru" },
    { id_state: "16", name: "Paso Del Rey" },
    { id_state: "16", name: "Pavon" },
    { id_state: "16", name: "Penino" },
    { id_state: "16", name: "Perico Perez" },
    { id_state: "16", name: "Picada Gambetta" },
    { id_state: "16", name: "Playa Pascual" },
    { id_state: "16", name: "Puntas De Cagancha" },
    { id_state: "16", name: "Puntas De Cañada Grande" },
    { id_state: "16", name: "Puntas De Chamizo" },
    { id_state: "16", name: "Puntas De Gregorío" },
    { id_state: "16", name: "Puntas De Laurel" },
    { id_state: "16", name: "Puntas De Tropa Vieja" },
    { id_state: "16", name: "Puntas De Valdez" },
    { id_state: "16", name: "Radial Ruta 3" },
    { id_state: "16", name: "Rafael Perazza" },
    { id_state: "16", name: "Raigon" },
    { id_state: "16", name: "Rincón De Albano" },
    { id_state: "16", name: "Rincón De Arazati" },
    { id_state: "16", name: "Rincón De Arias" },
    { id_state: "16", name: "Rincón De Buschental" },
    { id_state: "16", name: "Rincón De Cufre" },
    { id_state: "16", name: "Rincón De La Bolsa" },
    { id_state: "16", name: "Rincón De La Torre" },
    { id_state: "16", name: "Rincón De Nazareth" },
    { id_state: "16", name: "Rincón Del Pino" },
    { id_state: "16", name: "Rocho" },
    { id_state: "16", name: "Rodriguez" },
    { id_state: "16", name: "Safici" },
    { id_state: "16", name: "San Fernando" },
    { id_state: "16", name: "San Fernando Chico" },
    { id_state: "16", name: "San Gregorío" },
    { id_state: "16", name: "San José De Mayo" },
    { id_state: "16", name: "Santa Monica" },
    { id_state: "16", name: "Sauce" },
    { id_state: "16", name: "Sauce Chico" },
    { id_state: "16", name: "Scavino" },
    { id_state: "16", name: "Tabarez" },
    { id_state: "16", name: "Tala De Pereira" },
    { id_state: "16", name: "Tranquera Colorada" },
    { id_state: "16", name: "Tropas Viejas" },
    { id_state: "16", name: "Tropezon" },
    { id_state: "16", name: "Valdez Chico" },
    { id_state: "16", name: "Villa Maria" },
    { id_state: "16", name: "Villa Olimpica" },
    { id_state: "16", name: "Villa Rives" },
    { id_state: "16", name: "Zanja Honda" },
    { id_state: "17", name: "Altos Del Perdido" },
    { id_state: "17", name: "Ampliacion Larrañaga" },
    { id_state: "17", name: "Arenal Chico" },
    { id_state: "17", name: "Arroyo Del Medio" },
    { id_state: "17", name: "Arroyo Grande" },
    { id_state: "17", name: "Asencio" },
    { id_state: "17", name: "Azotea De Vera" },
    { id_state: "17", name: "Bajos Del Perdido" },
    { id_state: "17", name: "Bequelo" },
    { id_state: "17", name: "Bizcocho" },
    { id_state: "17", name: "Buena Vista" },
    { id_state: "17", name: "Cañada Magallanes" },
    { id_state: "17", name: "Cañada Nieto" },
    { id_state: "17", name: "Cañada Paraguaya" },
    { id_state: "17", name: "Cardona" },
    { id_state: "17", name: "Castillos" },
    { id_state: "17", name: "Cerro Alegre" },
    { id_state: "17", name: "Cerro Vera" },
    { id_state: "17", name: "Chacras De Dolores" },
    { id_state: "17", name: "Chacras De Mercedes" },
    { id_state: "17", name: "Cololo" },
    { id_state: "17", name: "Colonia Concordia" },
    { id_state: "17", name: "Colonia Diaz" },
    { id_state: "17", name: "Colonia Santa Clara" },
    { id_state: "17", name: "Colonia Uruguaya" },
    { id_state: "17", name: "Coquimbo" },
    { id_state: "17", name: "Corralito" },
    { id_state: "17", name: "Costa Del Aguila" },
    { id_state: "17", name: "Costas Del Perdido" },
    { id_state: "17", name: "Cuatro Bocas De Buena Vista" },
    { id_state: "17", name: "Cuchilla Del Corralito" },
    { id_state: "17", name: "Cuchilla Del Perdido" },
    { id_state: "17", name: "Cueva Del Tigre" },
    { id_state: "17", name: "Dolores" },
    { id_state: "17", name: "Duraznito" },
    { id_state: "17", name: "Egaña" },
    { id_state: "17", name: "El Aguila" },
    { id_state: "17", name: "El Tala" },
    { id_state: "17", name: "Espinillo" },
    { id_state: "17", name: "Garula" },
    { id_state: "17", name: "Grito De Asencio" },
    { id_state: "17", name: "José Enrique Rodo" },
    { id_state: "17", name: "La Concordia" },
    { id_state: "17", name: "La Laguna" },
    { id_state: "17", name: "La Loma" },
    { id_state: "17", name: "La Palma" },
    { id_state: "17", name: "La Tabla" },
    { id_state: "17", name: "Lares" },
    { id_state: "17", name: "Las Maulas" },
    { id_state: "17", name: "Lata Del Perdido" },
    { id_state: "17", name: "Maciel" },
    { id_state: "17", name: "Mercedes" },
    { id_state: "17", name: "Monzon" },
    { id_state: "17", name: "Olivera" },
    { id_state: "17", name: "Palmitas" },
    { id_state: "17", name: "Palo Solo" },
    { id_state: "17", name: "Parada Suarez" },
    { id_state: "17", name: "Paso De La Arena" },
    { id_state: "17", name: "Paso De Ramos" },
    { id_state: "17", name: "Pedro Chico" },
    { id_state: "17", name: "Perseverano" },
    { id_state: "17", name: "Progreso" },
    { id_state: "17", name: "Pueblo Palmar" },
    { id_state: "17", name: "Puntas De Arenales" },
    { id_state: "17", name: "Puntas De Durazno" },
    { id_state: "17", name: "Puntas De San Salvador" },
    { id_state: "17", name: "Puntas Del Tala" },
    { id_state: "17", name: "Rincón De Cañada Nieto" },
    { id_state: "17", name: "Rincón De Cololo" },
    { id_state: "17", name: "Rincón De Ruiz" },
    { id_state: "17", name: "Risso" },
    { id_state: "17", name: "San Dios" },
    { id_state: "17", name: "San Martin" },
    { id_state: "17", name: "Santa Blanca" },
    { id_state: "17", name: "Santa Catalina" },
    { id_state: "17", name: "Sarandí Chico" },
    { id_state: "17", name: "Unidad Cooperaria No 1" },
    { id_state: "17", name: "Villa Alejandrina" },
    { id_state: "17", name: "Villa Darwin" },
    { id_state: "17", name: "Villa Soriano" },
    { id_state: "17", name: "Zanja Honda" },
    { id_state: "18", name: "Achar" },
    { id_state: "18", name: "Ansina" },
    { id_state: "18", name: "Arroyo Del Medio" },
    { id_state: "18", name: "Ataque" },
    { id_state: "18", name: "Balnearío Ipora" },
    { id_state: "18", name: "Bañado De Cañas" },
    { id_state: "18", name: "Bañado De Rocha" },
    { id_state: "18", name: "Barrío La Matutina" },
    { id_state: "18", name: "Barrío Libertad" },
    { id_state: "18", name: "Blanquillos" },
    { id_state: "18", name: "Cañada Del Estado" },
    { id_state: "18", name: "Cañas" },
    { id_state: "18", name: "Caraguata Al Norte" },
    { id_state: "18", name: "Cardoso" },
    { id_state: "18", name: "Cardozo Chico" },
    { id_state: "18", name: "Carpinteria" },
    { id_state: "18", name: "Cerro Batovi" },
    { id_state: "18", name: "Cerro Chato" },
    { id_state: "18", name: "Cerro De Pastoreo" },
    { id_state: "18", name: "Cerro De Pereira" },
    { id_state: "18", name: "Cerro Del Arbolito" },
    { id_state: "18", name: "Cerros De Clara" },
    { id_state: "18", name: "Chamberlain" },
    { id_state: "18", name: "Charata" },
    { id_state: "18", name: "Churchill" },
    { id_state: "18", name: "Cinco Sauces" },
    { id_state: "18", name: "Clara" },
    { id_state: "18", name: "Clavijo" },
    { id_state: "18", name: "Colman" },
    { id_state: "18", name: "Costas De Caraguata" },
    { id_state: "18", name: "Costas De Tres Cruces" },
    { id_state: "18", name: "Coyo Martinez" },
    { id_state: "18", name: "Cruz De Los Caminos" },
    { id_state: "18", name: "Cuchilla De La Casa De Piedra" },
    { id_state: "18", name: "Cuchilla De La Palma" },
    { id_state: "18", name: "Cuchilla De Laureles" },
    { id_state: "18", name: "Cuchilla Del Ombu" },
    { id_state: "18", name: "Curtina" },
    { id_state: "18", name: "El Empalme" },
    { id_state: "18", name: "Estación Menendez" },
    { id_state: "18", name: "Frigorifico Modelo" },
    { id_state: "18", name: "Heriberto" },
    { id_state: "18", name: "La Aldea" },
    { id_state: "18", name: "La Bolsa 01" },
    { id_state: "18", name: "La Bolsa 02" },
    { id_state: "18", name: "La Hilera" },
    { id_state: "18", name: "La Palma" },
    { id_state: "18", name: "La Pedrera" },
    { id_state: "18", name: "Lambare" },
    { id_state: "18", name: "Larrayos" },
    { id_state: "18", name: "Las Arenas" },
    { id_state: "18", name: "Las Chircas" },
    { id_state: "18", name: "Las Pajas" },
    { id_state: "18", name: "Las Toscas" },
    { id_state: "18", name: "Laura" },
    { id_state: "18", name: "Laureles" },
    { id_state: "18", name: "Lavalleja" },
    { id_state: "18", name: "Los Cerros" },
    { id_state: "18", name: "Los Coitinhos" },
    { id_state: "18", name: "Los Cuadrados" },
    { id_state: "18", name: "Los Feos" },
    { id_state: "18", name: "Los Furtados" },
    { id_state: "18", name: "Los Garcia" },
    { id_state: "18", name: "Los Gomez" },
    { id_state: "18", name: "Los Laureles" },
    { id_state: "18", name: "Los Malavares" },
    { id_state: "18", name: "Los Ortices" },
    { id_state: "18", name: "Los Rodriguez" },
    { id_state: "18", name: "Los Rosanos" },
    { id_state: "18", name: "Los Rosas" },
    { id_state: "18", name: "Los Semper" },
    { id_state: "18", name: "Los Vazquez" },
    { id_state: "18", name: "Martinote" },
    { id_state: "18", name: "Minuano" },
    { id_state: "18", name: "Montevideo Chico" },
    { id_state: "18", name: "Once Cerros" },
    { id_state: "18", name: "Pampa" },
    { id_state: "18", name: "Paso Casildo" },
    { id_state: "18", name: "Paso De Ceferino" },
    { id_state: "18", name: "Paso De Las Carretas" },
    { id_state: "18", name: "Paso De Las Flores" },
    { id_state: "18", name: "Paso De Los Novillos" },
    { id_state: "18", name: "Paso De Los Toros" },
    { id_state: "18", name: "Paso De Perez" },
    { id_state: "18", name: "Paso Del Cerro" },
    { id_state: "18", name: "Paso Del Medio" },
    { id_state: "18", name: "Paso Hondo" },
    { id_state: "18", name: "Paso Livindo" },
    { id_state: "18", name: "Paso Victor" },
    { id_state: "18", name: "Peralta" },
    { id_state: "18", name: "Picada De Cuello" },
    { id_state: "18", name: "Pueblo Clavijo" },
    { id_state: "18", name: "Pueblo De Arriba" },
    { id_state: "18", name: "Pueblo Del Barro" },
    { id_state: "18", name: "Punta De Carretera" },
    { id_state: "18", name: "Puntas De Cinco Sauces" },
    { id_state: "18", name: "Puntas De Laureles" },
    { id_state: "18", name: "Rincón De Freitas" },
    { id_state: "18", name: "Rincón De Giloca" },
    { id_state: "18", name: "Rincón De La Aldea" },
    { id_state: "18", name: "Rincón De La Bolsa" },
    { id_state: "18", name: "Rincón De La Laguna" },
    { id_state: "18", name: "Rincón De Los Machado" },
    { id_state: "18", name: "Rincón De Pereira" },
    { id_state: "18", name: "Rincón De Zamora" },
    { id_state: "18", name: "Rincón Del Bonete" },
    { id_state: "18", name: "Rivera Chico" },
    { id_state: "18", name: "San Benito" },
    { id_state: "18", name: "San Gregorío De Polanco" },
    { id_state: "18", name: "San Joaquín" },
    { id_state: "18", name: "Sauce De Batovi" },
    { id_state: "18", name: "Sauce De Tranqueras" },
    { id_state: "18", name: "Sauce Solo" },
    { id_state: "18", name: "Sauce Solo Del Río Negro" },
    { id_state: "18", name: "Tacuarembó" },
    { id_state: "18", name: "Tacuarembó Chico" },
    { id_state: "18", name: "Tierras Coloradas" },
    { id_state: "18", name: "Tres Guitarras" },
    { id_state: "18", name: "Turupi" },
    { id_state: "18", name: "Valle Eden" },
    { id_state: "18", name: "Zambullon" },
    { id_state: "18", name: "Zapara" },
    { id_state: "18", name: "Zapucay" },
    { id_state: "19", name: "Acosta" },
    { id_state: "19", name: "Arrayanes De Cebollati" },
    { id_state: "19", name: "Arrayanes De Corral De Cebollati" },
    { id_state: "19", name: "Arrocera Bonomo" },
    { id_state: "19", name: "Arrocera El Tigre" },
    { id_state: "19", name: "Arrocera La Catumbera" },
    { id_state: "19", name: "Arrocera La Querencia" },
    { id_state: "19", name: "Arrocera Las Palmas" },
    { id_state: "19", name: "Arrocera Los Ceibos" },
    { id_state: "19", name: "Arrocera Los Teros" },
    { id_state: "19", name: "Arrocera Mini" },
    { id_state: "19", name: "Arrocera Procipa" },
    { id_state: "19", name: "Arrocera Rincón" },
    { id_state: "19", name: "Arrocera San Fernando" },
    { id_state: "19", name: "Arrocera Santa Fe" },
    { id_state: "19", name: "Arrocera Zapata" },
    { id_state: "19", name: "Arrozal Treinta Y Tres" },
    { id_state: "19", name: "Averías" },
    { id_state: "19", name: "Avestruz Chico" },
    { id_state: "19", name: "Bañado De Oro" },
    { id_state: "19", name: "Barrío Abreu" },
    { id_state: "19", name: "Cañada Chica" },
    { id_state: "19", name: "Cañada De Las Piedras" },
    { id_state: "19", name: "Cañada Del Sauce" },
    { id_state: "19", name: "Cerro Chato" },
    { id_state: "19", name: "Cerro Pelado" },
    { id_state: "19", name: "Cerros De Amaro" },
    { id_state: "19", name: "Cipa Cebollati" },
    { id_state: "19", name: "Cipa Olimar" },
    { id_state: "19", name: "Cipa Secador" },
    { id_state: "19", name: "Corrales De Cebollati" },
    { id_state: "19", name: "Costas De Tacuari" },
    { id_state: "19", name: "Costas Del Arroyo Malo" },
    { id_state: "19", name: "Costas Del Sarandí" },
    { id_state: "19", name: "Cuchilla De Dionisio" },
    { id_state: "19", name: "Cuchilla De Olmos" },
    { id_state: "19", name: "Ejido De Treinta Y Tres" },
    { id_state: "19", name: "El Bellaco" },
    { id_state: "19", name: "El Carmen" },
    { id_state: "19", name: "El Catete" },
    { id_state: "19", name: "Estación Rincón" },
    { id_state: "19", name: "Gral. Enrique Martinez" },
    { id_state: "19", name: "Higuerones" },
    { id_state: "19", name: "Julio Maria Sanz" },
    { id_state: "19", name: "La Calavera" },
    { id_state: "19", name: "La Calera" },
    { id_state: "19", name: "La Lata" },
    { id_state: "19", name: "Las Chacras" },
    { id_state: "19", name: "Las Pavas" },
    { id_state: "19", name: "Lechiguana De Corrales" },
    { id_state: "19", name: "Los Ceibos" },
    { id_state: "19", name: "Maria Albina" },
    { id_state: "19", name: "Maria Isabel" },
    { id_state: "19", name: "Mate Dulce" },
    { id_state: "19", name: "Mendizabal" },
    { id_state: "19", name: "Molles De Olimar" },
    { id_state: "19", name: "Noques De Olimar Chico" },
    { id_state: "19", name: "Olimar Grande" },
    { id_state: "19", name: "Palo A Pique" },
    { id_state: "19", name: "Panteon" },
    { id_state: "19", name: "Paso Ancho" },
    { id_state: "19", name: "Paso De La Atahona" },
    { id_state: "19", name: "Paso De La Laguna" },
    { id_state: "19", name: "Paso De Piriz" },
    { id_state: "19", name: "Paso Del Sauce" },
    { id_state: "19", name: "Poblado Alonzo" },
    { id_state: "19", name: "Puntas De Leóncho" },
    { id_state: "19", name: "Puntas De Los Ceibos" },
    { id_state: "19", name: "Puntas De Quebracho" },
    { id_state: "19", name: "Puntas Del Oro" },
    { id_state: "19", name: "Puntas Del Parao" },
    { id_state: "19", name: "Rincón De Gadea" },
    { id_state: "19", name: "Rincón De Iguini" },
    { id_state: "19", name: "Rincón De Los Francos" },
    { id_state: "19", name: "Rincón De Quintana" },
    { id_state: "19", name: "Rincón De Urtubey" },
    { id_state: "19", name: "Santa Clara De Olimar" },
    { id_state: "19", name: "Sauce De Corrales" },
    { id_state: "19", name: "Sierra Del Yerbal" },
    { id_state: "19", name: "Siete Casas" },
    { id_state: "19", name: "Treinta Y Tres" },
    { id_state: "19", name: "Verde Alto" },
    { id_state: "19", name: "Vergara" },
    { id_state: "19", name: "Villa Passano" },
    { id_state: "19", name: "Villa Sara" },
    { id_state: "19", name: "Yerbal Chico" },
    { id_state: "19", name: "Yerbalito" }       
]